### ISSUE TITLE
Wine on Android crashes

### ISSUE THREAD

**Issue by kawanakaiku** [ptitSeb/box64#1043]
I built latest Box64 and Wine 8.18. The built Wine works fine on x86_64 machine. When I try running ```wine cmd```, the cmd process starts but it crashes immediately after typing any key. The log with gdb is below.

```
~ $ BOX64_JITGDB=1 box64 wine cmd
Launch gdb on segfault
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on Kryo-4XX-Silver 
Kryo-4XX-Gold with 8 Cores
Box64 with Dynarec v0.2.5  built on Oct 26 2023 10:21:15
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Warning, older then 2.34 pthread_kill not found, using current one
Counted 54 Env var
BOX64 try to Preload /data/data/com.termux/files/usr/lib/libtermux-exec.so
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/system/lib64/
BOX64 BIN PATH: ./:bin/:/data/data/com.termux/files/usr/bin/
Looking for wine
argv[1]="cmd"
Rename process to "wine"
Warning, cannot pre-load of /data/data/com.termux/files/usr/lib/libtermux-exec.so
Using native(wrapped) libdl.so
Using native(wrapped) libc.so
Using emulated /data/data/com.termux/files/usr/bin/../lib/wine/x86_64-unix/ntdll.so
Launch gdb on segfault
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on Kryo-4XX-Silver 
Kryo-4XX-Gold with 8 Cores
Box64 with Dynarec v0.2.5  built on Oct 26 2023 10:21:15
BOX64: Wine preloader detected, loading "/data/data/com.termux/files/usr/bin/wine" directly
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Warning, older then 2.34 pthread_kill not found, using current one
Counted 56 Env var
BOX64 try to Preload /data/data/com.termux/files/usr/lib/libtermux-exec.so
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/system/lib64/
BOX64 BIN PATH: ./:bin/:/data/data/com.termux/files/usr/bin/
Looking for /data/data/com.termux/files/usr/bin/wine
argv[1]="cmd"
Rename process to "wine"
Warning, cannot pre-load of /data/data/com.termux/files/usr/lib/libtermux-exec.so
Using native(wrapped) libdl.so
Using native(wrapped) libc.so
Using emulated /data/data/com.termux/files/usr/bin/../lib/wine/x86_64-unix/ntdll.so
Launch gdb on segfault
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on Kryo-4XX-Silver 
Kryo-4XX-Gold with 8 Cores
Box64 with Dynarec v0.2.5  built on Oct 26 2023 10:21:15
BOX64: Wine preloader detected, loading "/data/data/com.termux/files/usr/bin/wine" directly
BOX64: Wine64 detected, WINEPRELOADRESERVE="140000000-140032000"
Warning, older then 2.34 pthread_kill not found, using current one
Counted 58 Env var
BOX64 try to Preload /data/data/com.termux/files/usr/lib/libtermux-exec.so
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/system/lib64/
BOX64 BIN PATH: ./:bin/:/data/data/com.termux/files/usr/bin/
Looking for /data/data/com.termux/files/usr/bin/wine
argv[1]="C:\windows\system32\conhost.exe"
argv[2]="--unix"
argv[3]="--width"
argv[4]="106"
argv[5]="--height"
argv[6]="68"
argv[7]="--server"
argv[8]="0x10"
Rename process to "wine"
Warning, cannot pre-load of /data/data/com.termux/files/usr/lib/libtermux-exec.so
Using native(wrapped) libdl.so
Using native(wrapped) libc.so
Using emulated /data/data/com.termux/files/usr/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /data/data/com.termux/files/usr/lib/wine/x86_64-unix/win32u.so
Using native(wrapped) libm.so
Using native(wrapped) libfreetype.so
Using emulated /data/data/com.termux/files/usr/lib/wine/x86_64-unix/win32u.so
Using native(wrapped) libm.so
Using native(wrapped) libfreetype.so
Launch gdb on segfault
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on Kryo-4XX-Silver 
Kryo-4XX-Gold with 8 Cores
Box64 with Dynarec v0.2.5  built on Oct 26 2023 10:21:15
BOX64: Wine preloader detected, loading "/data/data/com.termux/files/usr/bin/wine" directly
BOX64: Wine64 detected, WINEPRELOADRESERVE="140000000-1400f3000"
Warning, older then 2.34 pthread_kill not found, using current one
Counted 58 Env var
BOX64 try to Preload /data/data/com.termux/files/usr/lib/libtermux-exec.so
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/system/lib64/
BOX64 BIN PATH: ./:bin/:/data/data/com.termux/files/usr/bin/
Looking for /data/data/com.termux/files/usr/bin/wine
argv[1]="C:\windows\system32\cmd.exe"
Rename process to "wine"
Warning, cannot pre-load of /data/data/com.termux/files/usr/lib/libtermux-exec.so
Using native(wrapped) libdl.so
Using native(wrapped) libc.so
Using emulated /data/data/com.termux/files/usr/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /data/data/com.termux/files/usr/lib/wine/x86_64-unix/win32u.so
Using native(wrapped) libm.so
Using native(wrapped) libfreetype.so
Microsoft Windows 10.0.18362

Z:\data\data\com.termux\files\home>Using emulated /data/data/com.termux/files/usr/lib/wine/x86_64-unix/win
ex11.so
Using native(wrapped) libX11.so
Waiting for gdb (pid 10949)...
GNU gdb (GDB) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-android".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 10949
[New LWP 10960]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/data/data/com.termux/files/usr/lib/libthread_db.so".
0x0000007b3322dff4 in read () from /apex/com.android.runtime/lib64/bionic/libc.so
(gdb)
#0  0x0000007b3322dff4 in read () from /apex/com.android.runtime/lib64/bionic/libc.so
#1  0x0000007b3313f5dc in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

By the way,  Wine 8.18 with Box86 is working great.

**Comment by mcagabe19** [comment]
uhh it's native termux
