### ISSUE TITLE
Failed cmake Ubuntu 18.04 aarch64

### ISSUE THREAD

**Issue by KhanhNguyen9872** [ptitSeb/box64#1056]
## OS
```bash
root@localhost:~/box86/build# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

root@localhost:~/box86/build# uname -a
Linux localhost 4.9.270-g862f51bac900-ab7613625 #0 SMP PREEMPT Thu Aug 5 07:04:42 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

## Error
```bash
root@localhost:~/box86/build# cmake .. -DARM_DYNAREC=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBAD_SIGNAL=ON -DSD845=ON
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3")
-- The C compiler identification is GNU 7.5.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:712 (target_link_libraries):
  Target "interpreter" of type OBJECT_LIBRARY may not be linked into another
  target.  One may link only to STATIC or SHARED libraries, or to executables
  with the ENABLE_EXPORTS property set.


-- Configuring incomplete, errors occurred!
See also "/root/box86/build/CMakeFiles/CMakeOutput.log".
```

## CMakeOutput.log
```bash
root@localhost:~/box86/build# cat "/root/box86/build/CMakeFiles/CMakeOutput.log"
The system is: Linux - 4.9.270-g862f51bac900-ab7613625 - aarch64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/arm-linux-gnueabihf-gcc
Build flags:
Id flags:

The output was:
0


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"

The C compiler identification is GNU, found in "/root/box86/build/CMakeFiles/3.10.2/CompilerIdC/a.out"

Determining if the C compiler works passed with the following output:
Change Dir: /root/box86/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_db2d2/fast"
/usr/bin/make -f CMakeFiles/cmTC_db2d2.dir/build.make CMakeFiles/cmTC_db2d2.dir/build
make[1]: Entering directory '/root/box86/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_db2d2.dir/testCCompiler.c.o
/usr/bin/arm-linux-gnueabihf-gcc    -o CMakeFiles/cmTC_db2d2.dir/testCCompiler.c.o   -c /root/box86/build/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTC_db2d2
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_db2d2.dir/link.txt --verbose=1
/usr/bin/arm-linux-gnueabihf-gcc      CMakeFiles/cmTC_db2d2.dir/testCCompiler.c.o  -o cmTC_db2d2
make[1]: Leaving directory '/root/box86/build/CMakeFiles/CMakeTmp'


Detecting C compiler ABI info compiled with the following output:
Change Dir: /root/box86/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_03b7a/fast"
/usr/bin/make -f CMakeFiles/cmTC_03b7a.dir/build.make CMakeFiles/cmTC_03b7a.dir/build
make[1]: Entering directory '/root/box86/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_03b7a.dir/CMakeCCompilerABI.c.o
/usr/bin/arm-linux-gnueabihf-gcc    -o CMakeFiles/cmTC_03b7a.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake-3.10/Modules/CMakeCCompilerABI.c
Linking C executable cmTC_03b7a
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_03b7a.dir/link.txt --verbose=1
/usr/bin/arm-linux-gnueabihf-gcc     -v CMakeFiles/cmTC_03b7a.dir/CMakeCCompilerABI.c.o  -o cmTC_03b7a
Using built-in specs.
COLLECT_GCC=/usr/bin/arm-linux-gnueabihf-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc-cross/arm-linux-gnueabihf/7/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-multiarch --enable-multilib --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --disable-werror --enable-multilib --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=arm-linux-gnueabihf --program-prefix=arm-linux-gnueabihf- --includedir=/usr/arm-linux-gnueabihf/include
Thread model: posix
gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04)
COMPILER_PATH=/usr/lib/gcc-cross/arm-linux-gnueabihf/7/:/usr/lib/gcc-cross/arm-linux-gnueabihf/7/:/usr/lib/gcc-cross/arm-linux-gnueabihf/:/usr/lib/gcc-cross/arm-linux-gnueabihf/7/:/usr/lib/gcc-cross/arm-linux-gnueabihf/:/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/bin/
LIBRARY_PATH=/usr/lib/gcc-cross/arm-linux-gnueabihf/7/:/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib/:/lib/../lib/:/usr/lib/arm-linux-gnueabihf/:/usr/lib/../lib/:/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_03b7a' '-march=armv7-a' '-mfloat-abi=hard' '-mfpu=vfpv3-d16' '-mthumb' '-mtls-dialect=gnu'
 /usr/lib/gcc-cross/arm-linux-gnueabihf/7/collect2 -plugin /usr/lib/gcc-cross/arm-linux-gnueabihf/7/liblto_plugin.so -plugin-opt=/usr/lib/gcc-cross/arm-linux-gnueabihf/7/lto-wrapper -plugin-opt=-fresolution=/tmp/ccNAq46e.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -dynamic-linker /lib/ld-linux-armhf.so.3 -X --hash-style=gnu --as-needed -m armelf_linux_eabi -pie -z now -z relro -o cmTC_03b7a /usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib/Scrt1.o /usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib/crti.o /usr/lib/gcc-cross/arm-linux-gnueabihf/7/crtbeginS.o -L/usr/lib/gcc-cross/arm-linux-gnueabihf/7 -L/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib -L/lib/../lib -L/usr/lib/arm-linux-gnueabihf -L/usr/lib/../lib -L/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib CMakeFiles/cmTC_03b7a.dir/CMakeCCompilerABI.c.o -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc-cross/arm-linux-gnueabihf/7/crtendS.o /usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib/crtn.o
COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_03b7a' '-march=armv7-a' '-mfloat-abi=hard' '-mfpu=vfpv3-d16' '-mthumb' '-mtls-dialect=gnu'
make[1]: Leaving directory '/root/box86/build/CMakeFiles/CMakeTmp'


Parsed C implicit link information from above output:
  link line regex: [^( *|.*[/\])(ld|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\]+-)?ld|collect2)[^/\]*( |$)]
  ignore line: [Change Dir: /root/box86/build/CMakeFiles/CMakeTmp]
  ignore line: []
  ignore line: [Run Build Command:"/usr/bin/make" "cmTC_03b7a/fast"]
  ignore line: [/usr/bin/make -f CMakeFiles/cmTC_03b7a.dir/build.make CMakeFiles/cmTC_03b7a.dir/build]
  ignore line: [make[1]: Entering directory '/root/box86/build/CMakeFiles/CMakeTmp']
  ignore line: [Building C object CMakeFiles/cmTC_03b7a.dir/CMakeCCompilerABI.c.o]
  ignore line: [/usr/bin/arm-linux-gnueabihf-gcc    -o CMakeFiles/cmTC_03b7a.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake-3.10/Modules/CMakeCCompilerABI.c]
  ignore line: [Linking C executable cmTC_03b7a]
  ignore line: [/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_03b7a.dir/link.txt --verbose=1]
  ignore line: [/usr/bin/arm-linux-gnueabihf-gcc     -v CMakeFiles/cmTC_03b7a.dir/CMakeCCompilerABI.c.o  -o cmTC_03b7a ]
  ignore line: [Using built-in specs.]
  ignore line: [COLLECT_GCC=/usr/bin/arm-linux-gnueabihf-gcc]
  ignore line: [COLLECT_LTO_WRAPPER=/usr/lib/gcc-cross/arm-linux-gnueabihf/7/lto-wrapper]
  ignore line: [Target: arm-linux-gnueabihf]
  ignore line: [Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-multiarch --enable-multilib --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --disable-werror --enable-multilib --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=arm-linux-gnueabihf --program-prefix=arm-linux-gnueabihf- --includedir=/usr/arm-linux-gnueabihf/include]
  ignore line: [Thread model: posix]
  ignore line: [gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) ]
  ignore line: [COMPILER_PATH=/usr/lib/gcc-cross/arm-linux-gnueabihf/7/:/usr/lib/gcc-cross/arm-linux-gnueabihf/7/:/usr/lib/gcc-cross/arm-linux-gnueabihf/:/usr/lib/gcc-cross/arm-linux-gnueabihf/7/:/usr/lib/gcc-cross/arm-linux-gnueabihf/:/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/bin/]
  ignore line: [LIBRARY_PATH=/usr/lib/gcc-cross/arm-linux-gnueabihf/7/:/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib/:/lib/../lib/:/usr/lib/arm-linux-gnueabihf/:/usr/lib/../lib/:/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/:/lib/:/usr/lib/]
  ignore line: [COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_03b7a' '-march=armv7-a' '-mfloat-abi=hard' '-mfpu=vfpv3-d16' '-mthumb' '-mtls-dialect=gnu']
  link line: [ /usr/lib/gcc-cross/arm-linux-gnueabihf/7/collect2 -plugin /usr/lib/gcc-cross/arm-linux-gnueabihf/7/liblto_plugin.so -plugin-opt=/usr/lib/gcc-cross/arm-linux-gnueabihf/7/lto-wrapper -plugin-opt=-fresolution=/tmp/ccNAq46e.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -dynamic-linker /lib/ld-linux-armhf.so.3 -X --hash-style=gnu --as-needed -m armelf_linux_eabi -pie -z now -z relro -o cmTC_03b7a /usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib/Scrt1.o /usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib/crti.o /usr/lib/gcc-cross/arm-linux-gnueabihf/7/crtbeginS.o -L/usr/lib/gcc-cross/arm-linux-gnueabihf/7 -L/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib -L/lib/../lib -L/usr/lib/arm-linux-gnueabihf -L/usr/lib/../lib -L/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib CMakeFiles/cmTC_03b7a.dir/CMakeCCompilerABI.c.o -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc-cross/arm-linux-gnueabihf/7/crtendS.o /usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib/crtn.o]
    arg [/usr/lib/gcc-cross/arm-linux-gnueabihf/7/collect2] ==> ignore
    arg [-plugin] ==> ignore
    arg [/usr/lib/gcc-cross/arm-linux-gnueabihf/7/liblto_plugin.so] ==> ignore
    arg [-plugin-opt=/usr/lib/gcc-cross/arm-linux-gnueabihf/7/lto-wrapper] ==> ignore
    arg [-plugin-opt=-fresolution=/tmp/ccNAq46e.res] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc_s] ==> ignore
    arg [-plugin-opt=-pass-through=-lc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc_s] ==> ignore
    arg [--sysroot=/] ==> ignore
    arg [--build-id] ==> ignore
    arg [--eh-frame-hdr] ==> ignore
    arg [-dynamic-linker] ==> ignore
    arg [/lib/ld-linux-armhf.so.3] ==> ignore
    arg [-X] ==> ignore
    arg [--hash-style=gnu] ==> ignore
    arg [--as-needed] ==> ignore
    arg [-m] ==> ignore
    arg [armelf_linux_eabi] ==> ignore
    arg [-pie] ==> ignore
    arg [-znow] ==> ignore
    arg [-zrelro] ==> ignore
    arg [-o] ==> ignore
    arg [cmTC_03b7a] ==> ignore
    arg [/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib/Scrt1.o] ==> ignore
    arg [/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib/crti.o] ==> ignore
    arg [/usr/lib/gcc-cross/arm-linux-gnueabihf/7/crtbeginS.o] ==> ignore
    arg [-L/usr/lib/gcc-cross/arm-linux-gnueabihf/7] ==> dir [/usr/lib/gcc-cross/arm-linux-gnueabihf/7]
    arg [-L/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib] ==> dir [/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib]
    arg [-L/lib/../lib] ==> dir [/lib/../lib]
    arg [-L/usr/lib/arm-linux-gnueabihf] ==> dir [/usr/lib/arm-linux-gnueabihf]
    arg [-L/usr/lib/../lib] ==> dir [/usr/lib/../lib]
    arg [-L/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib] ==> dir [/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib]
    arg [CMakeFiles/cmTC_03b7a.dir/CMakeCCompilerABI.c.o] ==> ignore
    arg [-lgcc] ==> lib [gcc]
    arg [--push-state] ==> ignore
    arg [--as-needed] ==> ignore
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [--pop-state] ==> ignore
    arg [-lc] ==> lib [c]
    arg [-lgcc] ==> lib [gcc]
    arg [--push-state] ==> ignore
    arg [--as-needed] ==> ignore
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [--pop-state] ==> ignore
    arg [/usr/lib/gcc-cross/arm-linux-gnueabihf/7/crtendS.o] ==> ignore
    arg [/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib/crtn.o] ==> ignore
  collapse library dir [/usr/lib/gcc-cross/arm-linux-gnueabihf/7] ==> [/usr/lib/gcc-cross/arm-linux-gnueabihf/7]
  collapse library dir [/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib] ==> [/usr/arm-linux-gnueabihf/lib]
  collapse library dir [/lib/../lib] ==> [/lib]
  collapse library dir [/usr/lib/arm-linux-gnueabihf] ==> [/usr/lib/arm-linux-gnueabihf]
  collapse library dir [/usr/lib/../lib] ==> [/usr/lib]
  collapse library dir [/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib] ==> [/usr/arm-linux-gnueabihf/lib]
  implicit libs: [gcc;gcc_s;c;gcc;gcc_s]
  implicit dirs: [/usr/lib/gcc-cross/arm-linux-gnueabihf/7;/usr/arm-linux-gnueabihf/lib;/lib;/usr/lib/arm-linux-gnueabihf;/usr/lib]
  implicit fwks: []




Detecting C [-std=c11] compiler features compiled with the following output:
Change Dir: /root/box86/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_57c81/fast"
/usr/bin/make -f CMakeFiles/cmTC_57c81.dir/build.make CMakeFiles/cmTC_57c81.dir/build
make[1]: Entering directory '/root/box86/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_57c81.dir/feature_tests.c.o
/usr/bin/arm-linux-gnueabihf-gcc   -std=c11 -o CMakeFiles/cmTC_57c81.dir/feature_tests.c.o   -c /root/box86/build/CMakeFiles/feature_tests.c
Linking C executable cmTC_57c81
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_57c81.dir/link.txt --verbose=1
/usr/bin/arm-linux-gnueabihf-gcc      CMakeFiles/cmTC_57c81.dir/feature_tests.c.o  -o cmTC_57c81
make[1]: Leaving directory '/root/box86/build/CMakeFiles/CMakeTmp'


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_restrict
    Feature record: C_FEATURE:1c_static_assert
    Feature record: C_FEATURE:1c_variadic_macros


Detecting C [-std=c99] compiler features compiled with the following output:
Change Dir: /root/box86/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_737ce/fast"
/usr/bin/make -f CMakeFiles/cmTC_737ce.dir/build.make CMakeFiles/cmTC_737ce.dir/build
make[1]: Entering directory '/root/box86/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_737ce.dir/feature_tests.c.o
/usr/bin/arm-linux-gnueabihf-gcc   -std=c99 -o CMakeFiles/cmTC_737ce.dir/feature_tests.c.o   -c /root/box86/build/CMakeFiles/feature_tests.c
Linking C executable cmTC_737ce
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_737ce.dir/link.txt --verbose=1
/usr/bin/arm-linux-gnueabihf-gcc      CMakeFiles/cmTC_737ce.dir/feature_tests.c.o  -o cmTC_737ce
make[1]: Leaving directory '/root/box86/build/CMakeFiles/CMakeTmp'


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:1c_variadic_macros


Detecting C [-std=c90] compiler features compiled with the following output:
Change Dir: /root/box86/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_9477e/fast"
/usr/bin/make -f CMakeFiles/cmTC_9477e.dir/build.make CMakeFiles/cmTC_9477e.dir/build
make[1]: Entering directory '/root/box86/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_9477e.dir/feature_tests.c.o
/usr/bin/arm-linux-gnueabihf-gcc   -std=c90 -o CMakeFiles/cmTC_9477e.dir/feature_tests.c.o   -c /root/box86/build/CMakeFiles/feature_tests.c
Linking C executable cmTC_9477e
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9477e.dir/link.txt --verbose=1
/usr/bin/arm-linux-gnueabihf-gcc      CMakeFiles/cmTC_9477e.dir/feature_tests.c.o  -o cmTC_9477e
make[1]: Leaving directory '/root/box86/build/CMakeFiles/CMakeTmp'


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:0c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:0c_variadic_macros
```

**Comment by ptitSeb** [comment]
Your cmake version is too old, you'll need a newer one to build box64.

**Comment by KhanhNguyen9872** [comment]
> Your cmake version is too old, you'll need a newer one to build box64.

thanks

**Comment by KhanhNguyen9872** [comment]
> Your cmake version is too old, you'll need a newer one to build box64.

how to get log box64, i want to report bug
```bash
root@localhost:/home/jxqy/gateway# box64 ./RankServer
Dynarec will try to make bigger blocks
Dynarec will not play it safe with x64 flags                                                    Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on unknown aarch64 cpu with 8 Cores                                                                      Params database has 32 entries                                                                  Counted 22 Env var                                                                              BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/bin/:/usr/bin/:/sbin/:/usr/sbin/:/usr/games/:/usr/local/games/
Looking for ./RankServer                                                                        Rename process to "RankServer"
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libdl.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1                                                                fatal error: rt_sigaction read failure

runtime stack:
runtime.throw(0x858480, 0x19)
        /root/go/src/runtime/panic.go:530 +0x90
runtime.getsig(0x40, 0x465670)
        /root/go/src/runtime/os1_linux.go:355 +0x81
runtime.initsig(0x9e3000)
        /root/go/src/runtime/signal1_unix.go:69 +0x89
runtime.mstart1()
        /root/go/src/runtime/proc.go:1091 +0xcd
runtime.mstart()
        /root/go/src/runtime/proc.go:1065 +0x72

goroutine 1 [runnable]:
runtime.main()
        /root/go/src/runtime/proc.go:105
runtime.goexit()
        /root/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /root/go/src/runtime/asm_amd64.s:1998 +0x1

```

**Comment by KhanhNguyen9872** [comment]
> > Your cmake version is too old, you'll need a newer one to build box64.
> 
> thanks

this error like this [issue](https://github.com/golang/go/issues/13024) but i'm run x86_64 on aarch64

**Comment by ptitSeb** [comment]
Ok, I have added a workaround. Pleas next time just create a new ticket, don't recycle a ticket that as nothing to do with the issue.

**Comment by KhanhNguyen9872** [comment]
> Ok, I have added a workaround. Pleas next time just create a new ticket, don't recycle a ticket that as nothing to do with the issue.

ok i know, thanks for your answer!

**Comment by KhanhNguyen9872** [comment]
> Ok, I have added a workaround. Pleas next time just create a new ticket, don't recycle a ticket that as nothing to do with the issue.
