### ISSUE TITLE
signal 28 received but handler not on signal stack - non-Go code set up signal handler without SA_ONSTACK flag

### ISSUE THREAD

**Issue by KhanhNguyen9872** [ptitSeb/box64#1067]
```bash
Dynarec will try to make bigger blocks
Dynarec will not play it safe with x64 flags
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on unknown aarch64 cpu with 8 Cores
Params database has 32 entries
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 22 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/bin/:/usr/bin/:/sbin/:/usr/sbin/:/usr/games/:/usr/local/games/
Looking for RankServer
Rename process to "RankServer"
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libdl.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Load account Finish: 0
Load gift Finish: 0
signal 28 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

goroutine 17 [running, locked to thread]:
runtime.throw(0x885b40, 0x39)
        /root/go/src/runtime/panic.go:530 +0x90 fp=0x8d3aec8 sp=0x8d3aeb0
runtime.sigNotOnStack(0x1c)
        /root/go/src/runtime/signal1_unix.go:308 +0x84 fp=0x8d3aee0 sp=0x8d3aec8
runtime.call32(0x0, 0x1007fed80, 0x1007fee08, 0x4)
        /root/go/src/runtime/asm_amd64.s:472 +0x3e fp=0x8d3af08 sp=0x8d3aee0
runtime.cgocallbackg1()
        /root/go/src/runtime/cgocall.go:267 +0x10c fp=0x8d3af40 sp=0x8d3af08
runtime.cgocallbackg()
        /root/go/src/runtime/cgocall.go:180 +0xd7 fp=0x8d3afa0 sp=0x8d3af40
runtime.cgocallback_gofunc(0x0, 0x0, 0x0)
        /root/go/src/runtime/asm_amd64.s:716 +0x60 fp=0x8d3afb0 sp=0x8d3afa0
runtime.goexit()
        /root/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0x8d3afb8 sp=0x8d3afb0

goroutine 1 [chan receive]:
main.procSigal.func1(0x8d122a0)
        /home2/buildagent/workspace/root/HK/BuildLinux/BuildLinuxBranch/FT-code-release/RankServer/RankServer.go:63 +0x78
main.procSigal()
        /home2/buildagent/workspace/root/HK/BuildLinux/BuildLinuxBranch/FT-code-release/RankServer/RankServer.go:88 +0x5e
main.main()
        /home2/buildagent/workspace/root/HK/BuildLinux/BuildLinuxBranch/FT-code-release/RankServer/RankServer.go:107 +0x45c

goroutine 5 [chan receive]:
github.com/glog.(*loggingT).flushDaemon(0x9e2b80)
        /root/gopath/src/github.com/glog/glog.go:890 +0x61
created by github.com/glog.init.1
        /root/gopath/src/github.com/glog/glog.go:410 +0x297

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
        /root/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
        /root/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /root/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [select, locked to thread]:
runtime.gopark(0x8a8b20, 0x8d29728, 0x800130, 0x6, 0x18, 0x2)
        /root/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0x8d29728, 0x0, 0x18)
        /root/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0x8d29728)
        /root/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
        /root/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
        /root/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [chan receive]:
database/sql.(*DB).connectionOpener(0x8e5a0b0)
        /root/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
        /root/go/src/database/sql/sql.go:493 +0x33f

goroutine 34 [syscall, locked to thread]:
runtime.goexit()
        /root/go/src/runtime/asm_amd64.s:1998 +0x1
```

**Comment by KhanhNguyen9872** [comment]
finally fixed, not problem from box64, sorry for this issue

**Comment by KhanhNguyen9872** [comment]
I see it's not the software, I tested it on Linux x86_64 and it works fine, how can I fix that? Do you have any solution? @ptitSeb

**Comment by ptitSeb** [comment]
I'm not sure. I need to analyse what GO expect there. It's probably code fix anyway, nothing that can be just tweaked away.

**Comment by KhanhNguyen9872** [comment]
> I'm not sure. I need to analyse what GO expect there. It's probably code fix anyway, nothing that can be just tweaked away.

can i send you 'RankServer' file?

**Comment by ptitSeb** [comment]
That can help yes

**Comment by KhanhNguyen9872** [comment]
> That can help yes

thanks a lot! [here](https://github.com/KhanhNguyen9872/PublicFile/releases/download/tempfiles/RankServer.7z) is file, how to run in readme.txt from this file

**Comment by KhanhNguyen9872** [comment]
> That can help yes

current this issue isn't fix, can you fix it? thanks

**Comment by KhanhNguyen9872** [comment]
finally, i found a way to fix this error
thanks
