### ISSUE TITLE
Failing to load libraries that are present in the current directory (as well custom directories specified in `BOX64_LD_LIBRARY_PATH`)

### ISSUE THREAD

**Issue by EpicBirb** [ptitSeb/box64#1823]
Used `termux-chroot` to compile box64 on Termux (natively) (device is non-rooted) (everything here was done remotely using ssh).
I attempted to run A Dance of Fire and Ice on my phone with the following libraries it asked for:

UnityPlayer.so
libm.so.6
libgcc_s.so.1
libpthread.so.0
libc.so.6

However it was only emulating the UnityPlayer.so and the other libraries weren't loading in. I've tried using the `BOX64_LD_LIBRARY_PATH` environmental variable to specify the paths for the libraries but it only managed to load in UnityPlayer.so and libgcc_s.so.1 from `/usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1`

All the other libraries were in the same directory as the UnityPlayer.so as well as some others in other directories since libc.so.6 and others weren't present on the system (so I downloaded them from an rpm). 

Image:
![image](https://github.com/user-attachments/assets/d06dbf60-abd2-455c-9174-73498632beb1)

**Comment by kde-yyds** [comment]
![Image](https://github.com/user-attachments/assets/53316f05-ff9d-4b1c-a0e3-a5ee8c0cf472)
I'm getting abort when trying to run a dance of fire and ice. Did you encounter this?

**Comment by kde-yyds** [comment]
> My guess is: you are missing some OpenGL function or something like that? You need to check the Player.log generated by unity. It's somehwere in `~/.config/unity3D/**EDITOR NAME**/**GAME NAME**/Player.log`

```
Using emulated /home/ikun/1/ADanceOfFireAndIce_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
MonoBleedingEdge detected, disable Dynarec BigBlock and enable Dynarec StrongMem
Using native(wrapped) libz.so.1
Mono path[0] = '/home/ikun/1/ADanceOfFireAndIce_Data/Managed'
Mono config path = '/home/ikun/1/ADanceOfFireAndIce_Data/MonoBleedingEdge/etc'

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x3f0411557e - /home/ikun/1/ADanceOfFireAndIce_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so : mono_breakpoint_clean_code
	0x3f040bdff9 - /home/ikun/1/ADanceOfFireAndIce_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so : mono_unity_backtrace_from_context
	0x3f04110da9 - /home/ikun/1/ADanceOfFireAndIce_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so : mono_breakpoint_clean_code
	0x30032d93 - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Entering thread summarizer pause from 0x521696662752x
Finished thread summarizer pause from 0x521696662752x.
Could not exec mono-hang-watchdog, expected on path '/home/ikun/1/ADanceOfFireAndIce_Data/MonoBleedingEdge/etc/../bin/mono-hang-watchdog' (errno 2)
Failed to create breadcrumb file (null)/crash_hash_0x1611c5d42

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 11568]
[New LWP 11567]
[New LWP 11566]
[New LWP 11565]
[New LWP 11564]
[New LWP 11563]
[New LWP 11562]
[New LWP 11561]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x000000797771e1a8 in ?? () from /usr/lib/libc.so.6
  Id   Target Id                                         Frame 
* 1    Thread 0x79778b54e0 (LWP 11556) "ADanceOfFireAnd" 0x000000797771e1a8 in ?? () from /usr/lib/libc.so.6
  2    Thread 0x795f6fef00 (LWP 11568) "SDLTimer"        0x000000797771e1a8 in ?? () from /usr/lib/libc.so.6
  3    Thread 0x79714eaf00 (LWP 11567) "AssetGarbageCol" 0x0000007977778724 in syscall () from /usr/lib/libc.so.6
  4    Thread 0x7971ffaf00 (LWP 11566) "AssetGarbageCol" 0x0000007977778724 in syscall () from /usr/lib/libc.so.6
  5    Thread 0x7972b0af00 (LWP 11565) "AssetGarbageCol" 0x0000007977778724 in syscall () from /usr/lib/libc.so.6
  6    Thread 0x797361af00 (LWP 11564) "AssetGarbageCol" 0x0000007977778724 in syscall () from /usr/lib/libc.so.6
  7    Thread 0x797412af00 (LWP 11563) "AssetGarbageCol" 0x0000007977778724 in syscall () from /usr/lib/libc.so.6
  8    Thread 0x7974c3af00 (LWP 11562) "AssetGarbageCol" 0x0000007977778724 in syscall () from /usr/lib/libc.so.6
  9    Thread 0x797576af00 (LWP 11561) "AssetGarbageCol" 0x0000007977778724 in syscall () from /usr/lib/libc.so.6

Thread 9 (Thread 0x797576af00 (LWP 11561) "AssetGarbageCol"):
#0  0x0000007977778724 in syscall () from /usr/lib/libc.so.6
#1  0x0000000034a58204 in my_syscall ()
#2  0x0000000034a97634 in ?? ()
#3  0x0000007976b78390 in ?? ()
#4  0x0000000067d69f00 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 8 (Thread 0x7974c3af00 (LWP 11562) "AssetGarbageCol"):
#0  0x0000007977778724 in syscall () from /usr/lib/libc.so.6
#1  0x0000000034a58204 in my_syscall ()
#2  0x0000000034a97634 in ?? ()
#3  0x0000007976b78390 in ?? ()
#4  0x0000000067d7c920 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 7 (Thread 0x797412af00 (LWP 11563) "AssetGarbageCol"):
#0  0x0000007977778724 in syscall () from /usr/lib/libc.so.6
#1  0x0000000034a58204 in my_syscall ()
#2  0x0000000034a97634 in ?? ()
#3  0x0000007976b78390 in ?? ()
#4  0x0000000067d9b0b0 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 6 (Thread 0x797361af00 (LWP 11564) "AssetGarbageCol"):
#0  0x0000007977778724 in syscall () from /usr/lib/libc.so.6
#1  0x0000000034a58204 in my_syscall ()
#2  0x0000000034a97634 in ?? ()
#3  0x0000007976b78390 in ?? ()
#4  0x0000000067d9b240 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 5 (Thread 0x7972b0af00 (LWP 11565) "AssetGarbageCol"):
#0  0x0000007977778724 in syscall () from /usr/lib/libc.so.6
#1  0x0000000034a58204 in my_syscall ()
#2  0x0000000034a97634 in ?? ()
#3  0x0000007976b78390 in ?? ()
#4  0x0000000067d9b3d0 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 4 (Thread 0x7971ffaf00 (LWP 11566) "AssetGarbageCol"):
#0  0x0000007977778724 in syscall () from /usr/lib/libc.so.6
#1  0x0000000034a58204 in my_syscall ()
#2  0x0000000034a97634 in ?? ()
#3  0x0000007976b78390 in ?? ()
#4  0x0000000067d989e0 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 3 (Thread 0x79714eaf00 (LWP 11567) "AssetGarbageCol"):
#0  0x0000007977778724 in syscall () from /usr/lib/libc.so.6
#1  0x0000000034a58204 in my_syscall ()
#2  0x0000000034a97634 in ?? ()
#3  0x0000007976b78390 in ?? ()
#4  0x0000000067d98b70 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 2 (Thread 0x795f6fef00 (LWP 11568) "SDLTimer"):
#0  0x000000797771e1a8 in ?? () from /usr/lib/libc.so.6
#1  0x0000007977711a54 in ?? () from /usr/lib/libc.so.6
#2  0x0000007977711de0 in ?? () from /usr/lib/libc.so.6
#3  0x000000797771e060 in ?? () from /usr/lib/libc.so.6
#4  0x0000007976bf91fc in ?? ()
#5  0x0000000067dd4b40 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 1 (Thread 0x79778b54e0 (LWP 11556) "ADanceOfFireAnd"):
#0  0x000000797771e1a8 in ?? () from /usr/lib/libc.so.6
#1  0x0000007977711a54 in ?? () from /usr/lib/libc.so.6
#2  0x0000007977711a90 in ?? () from /usr/lib/libc.so.6
#3  0x0000007977768160 in wait4 () from /usr/lib/libc.so.6
#4  0x000000795e4ab1f0 in ?? ()
#5  0x0000000000000002 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
[Inferior 1 (process 11556) detached]

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x30032d93):0x30032d83  a0 92 a7 34 00 00 00 00 c0 ee ea 34 00 00 00 00  ...4.......4....
0x30032d93  c3 00 00 70 05 ea 67 00 00 00 00 00 00 cc 53 43  ...p..g.......SC
0x30032da3  40 8c a8 34 00 00 00 00 60 64 eb 34 00 00 00 00  @..4....`d.4....
0x30032db3  c3 00 00 29 63 e9 67 00 00 00 00 00 00 cc 53 43  ...)c.g.......SC

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.OutOfMemoryException:.ctor <0x00017>
	  at <Module>:runtime_invoke_void__this___object <0x000ce>
=================================================================
NativeBT: /home/ikun/1/ADanceOfFireAndIce() [0x34a5993c]
NativeBT: linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x79778bb89c]
NativeBT: /usr/lib/libc.so.6(+0x870f8) [0x79777170f8]
NativeBT: /usr/lib/libc.so.6(gsignal+0x1c) [0x79776c6f9c]
NativeBT: /usr/lib/libc.so.6(abort+0x28) [0x79776b1938]
NativeBT: [0x795e4ad264]
EmulatedBT: box64(vsnprintf+0) [0x30030240]
EmulatedBT: /home/ikun/1/ADanceOfFireAndIce_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so+110dae [0x3f04110dae]
EmulatedBT: ??? [(nil)]
11556|SIGABRT @0x79777170f8 (???(/usr/lib/libc.so.6+0x870f8)) (x64pc=0x30030253/"???", rsp=0x797755d428, stack=0x7976d60000:0x7977560000 own=(nil) fp=(nil)), for accessing 0x3e900002d24 (code=-6/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x0000003f045be128 RSP-0x18:0x0000000000000000 RSP-0x10:0x0000000067ecc9f0 RSP-0x08:0x0000000000000000
RSP+0x00:0x0000003f04110dae RSP+0x08:0x0000000000000000 RSP+0x10:0x0000000000000002 RSP+0x18:0x0000000067ecce48
RAX:0x0000000000000042 RCX:0x000000797755cf30 RDX:0x0000003f04294826 RBX:0x000000797755cf50 
RSP:0x000000797755d428 RBP:0x0000000000000000 RSI:0x0000000000000400 RDI:0x000000797755cf50 
 R8:0x000000797755d190  R9:0x000000797755ce10 R10:0x0000003f04294826 R11:0x0000000000000035 
R12:0x0000000067ecc340 R13:0x0000003f0432dbc6 R14:0x0000000000000000 R15:0x0000000067ecc9f0 
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b FS:0x0043 GS:0x0053 

```

**Comment by kde-yyds** [comment]
I think not because of opengl because both panfrost and llvmpipe and softpipe have the same error

**Comment by ptitSeb** [comment]
I fyou are on a Rockchip SoC, make sure you built with the "BAD_SIGNAL" option.

**Comment by ptitSeb** [comment]
Everything Android also needs BAD_SIGNAL...

**Comment by kde-yyds** [comment]
> Everything Android also needs BAD_SIGNAL...

Okay. I will try to rebuild with this flag

**Comment by kde-yyds** [comment]
> Everything Android also needs BAD_SIGNAL...
It works now. Thanks
