### ISSUE TITLE
Protonup-qt appimage crashes with segfault

### ISSUE THREAD

**Issue by FoxbitDreamtail** [ptitSeb/box64#1930]
Running on Raspberry Pi 5 with MX Linux 23.4.

Reproduce the error by following these steps
1) In PiApps, install Steam which will install Box86 and Box64.
2) Download the Appimage of Protonup-qt from its official website.
3) Mark the appimage as executable(either by using `sudo chmod +x %filename%` or by right-clicking going to properties permissions and then ticking the allow executing as a program).
4) Open a terminal and launch app images like you would any other Linux executable, `./%filename%`.

The reason that this half is desirable is it permits you to manage proton versions and other compatibility applications for specific steam games and in some cases even allows you to run certain games under a Linux native layer which removes a layer of compatibility that you need to run through(a welcome addition, or should I say subtraction? lol)

**Comment by FoxbitDreamtail** [comment]
here's the terminal output when run:
`$ ./ProtonUp-Qt-2.10.2-x86_64.AppImage 
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A76 with 4 Cores
Will use Hardware counter measured at 54.0 MHz emulating 3.4 GHz
Params database has 91 entries
Box64 with Dynarec v0.3.1 b6cd19b7 built on Oct 13 2024 06:21:54
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 54 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/usr/local/bin/:/usr/bin/:/bin/:/usr/local/games/:/usr/games/:/sbin/:/usr/sbin/:/home/MXUser/.local/bin/
Looking for ./ProtonUp-Qt-2.10.2-x86_64.AppImage
Rename process to "ProtonUp-Qt-2.10.2-x86_64.AppImage"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libz.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using native(wrapped) libfuse.so.2
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A76 with 4 Cores
Will use Hardware counter measured at 54.0 MHz emulating 3.4 GHz
Params database has 91 entries
Box64 with Dynarec v0.3.1 b6cd19b7 built on Oct 13 2024 06:21:54
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 58 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/usr/local/bin/:/usr/bin/:/bin/:/usr/local/games/:/usr/games/:/sbin/:/usr/sbin/:/home/MXUser/.local/bin/
Looking for /tmp/.mount_ProtonDYTwRL/AppRun
Rename process to "AppRun"
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
ERROR: ld.so: object 'libapprun_hooks.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A76 with 4 Cores
Will use Hardware counter measured at 54.0 MHz emulating 3.4 GHz
Params database has 91 entries
Box64 with Dynarec v0.3.1 b6cd19b7 built on Oct 13 2024 06:21:54
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 102 Env var
BOX64 trying to Preload libapprun_hooks.so 
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/tmp/.mount_ProtonDYTwRL/usr/bin/:/tmp/.mount_ProtonDYTwRL/usr/lib/python3.10/:/tmp/.mount_ProtonDYTwRL/usr/lib/python3.10/encodings/:/tmp/.mount_ProtonDYTwRL/usr/lib/python3.10/test/:/tmp/.mount_ProtonDYTwRL/usr/local/bin/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/Cryptodome/Cipher/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/Cryptodome/Hash/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/Cryptodome/Math/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/Cryptodome/Protocol/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/Cryptodome/PublicKey/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/Cryptodome/Util/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/lib/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/libexec/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/designer/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/egldeviceintegrations/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/generic/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/iconengines/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/imageformats/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/networkinformation/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/platforminputcontexts/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/platforms/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/platformthemes/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/printsupport/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/qmltooling/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/sqldrivers/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/tls/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/wayland-decoration-client/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/wayland-graphics-integration-client/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/wayland-graphics-integration-server/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/wayland-shell-integration/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/xcbglintegrations/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/scripts/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/scripts/deploy_lib/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/scripts/deploy_lib/android/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/scripts/deploy_lib/android/recipes/PySide6/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/scripts/deploy_lib/android/recipes/shiboken6/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/scripts/project/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/scripts/qtpy2cpp_lib/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/charset_normalizer/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/shiboken6/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/yaml/:/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/zstandard/:/tmp/.mount_ProtonDYTwRL/usr/share/python3/:/tmp/.mount_ProtonDYTwRL/usr/share/python3/runtime.d/:/usr/local/bin/:/usr/bin/:/bin/:/usr/local/games/:/usr/games/:/sbin/:/usr/sbin/:/home/MXUser/.local/bin/
Looking for /tmp/.mount_ProtonDYTwRL/usr/bin/python3
argv[1]="-m"
argv[2]="pupgui2"
Rename process to "python3.10"
Using emulated /tmp/.mount_ProtonDYTwRL/lib/x86_64/libapprun_hooks.so
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) libresolv.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using native(wrapped) libm.so.6
Using native(wrapped) libexpat.so.1
Using native(wrapped) libz.so.1
Using emulated /tmp/.mount_ProtonDYTwRL/usr/lib/python3.10/lib-dynload/_bz2.cpython-310-x86_64-linux-gnu.so
Using native(wrapped) libbz2.so.1
Using emulated /tmp/.mount_ProtonDYTwRL/usr/lib/python3.10/lib-dynload/_lzma.cpython-310-x86_64-linux-gnu.so
Using native(wrapped) liblzma.so.5
Using emulated /tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/shiboken6/Shiboken.abi3.so
Using emulated /tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/shiboken6/libshiboken6.abi3.so.6.7
Using emulated /usr/lib/box64-x86_64-linux-gnu/libstdc++.so.6
Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
Warning: Weak Symbol _ITM_memcpyRtWn not found, cannot apply R_X86_64_JUMP_SLOT @0x3f0524f060 (0x9c0f6)
Warning: Weak Symbol _ITM_RU1 not found, cannot apply R_X86_64_JUMP_SLOT @0x3f0524f6a0 (0x9cd76)
Warning: Weak Symbol _ZGTtdlPv not found, cannot apply R_X86_64_JUMP_SLOT @0x3f0524fb00 (0x9d636)
Warning: Weak Symbol _ITM_RU8 not found, cannot apply R_X86_64_JUMP_SLOT @0x3f0524fff8 (0x9e026)
Warning: Weak Symbol _ITM_memcpyRnWt not found, cannot apply R_X86_64_JUMP_SLOT @0x3f052504a8 (0x9e986)
Warning: Weak Symbol _ZGTtnam not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05250c88 (0x9f946)
Using emulated /tmp/.mount_ProtonDYTwRL/usr/lib/python3.10/lib-dynload/_opcode.cpython-310-x86_64-linux-gnu.so
Using emulated /tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/QtCore.abi3.so
Using emulated /tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/libpyside6.abi3.so.6.7
Using emulated /tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/lib/libQt6Core.so.6
Error initializing native libicui18n.so.73 (last dlerror is libicui18n.so.73: cannot open shared object file: No such file or directory)
Using emulated /tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/lib/libicui18n.so.73
Error initializing native libicuuc.so.73 (last dlerror is libicuuc.so.73: cannot open shared object file: No such file or directory)
Using emulated /tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/lib/libicuuc.so.73
Using emulated /tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/lib/libicudata.so.73
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgthread-2.0.so.0
Using emulated /tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/QtGui.abi3.so
Using emulated /tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/lib/libQt6Gui.so.6
Using native(wrapped) libGL.so.1
Using native(wrapped) libEGL.so.1
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using emulated /tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/lib/libQt6DBus.so.6
Using native(wrapped) libxkbcommon.so.0
Using native(wrapped) libdbus-1.so.3
Look for eglQueryString in loaded elfs
Warning, function eglQueryString not found in lib libGL.so.1
Look for eglCreateContext in loaded elfs
Warning, function eglCreateContext not found in lib libGL.so.1
Look for eglGetCurrentDisplay in loaded elfs
Warning, function eglGetCurrentDisplay not found in lib libGL.so.1
Look for eglMakeCurrent in loaded elfs
Warning, function eglMakeCurrent not found in lib libGL.so.1
Look for eglGetConfigAttrib in loaded elfs
Warning, function eglGetConfigAttrib not found in lib libGL.so.1
Look for eglDestroyContext in loaded elfs
Warning, function eglDestroyContext not found in lib libGL.so.1
Look for eglGetError in loaded elfs
Warning, function eglGetError not found in lib libGL.so.1
Look for eglSwapInterval in loaded elfs
Warning, function eglSwapInterval not found in lib libGL.so.1
Look for eglChooseConfig in loaded elfs
Warning, function eglChooseConfig not found in lib libGL.so.1
Look for eglSwapBuffers in loaded elfs
Warning, function eglSwapBuffers not found in lib libGL.so.1
Look for eglCreatePbufferSurface in loaded elfs
Warning, function eglCreatePbufferSurface not found in lib libGL.so.1
Look for eglGetCurrentContext in loaded elfs
Warning, function eglGetCurrentContext not found in lib libGL.so.1
Look for eglGetConfigs in loaded elfs
Warning, function eglGetConfigs not found in lib libGL.so.1
Look for eglDestroySurface in loaded elfs
Warning, function eglDestroySurface not found in lib libGL.so.1
Look for eglGetCurrentSurface in loaded elfs
Warning, function eglGetCurrentSurface not found in lib libGL.so.1
Look for eglQueryContext in loaded elfs
Warning, function eglQueryContext not found in lib libGL.so.1
Error: Symbol FT_Get_Var_Design_Coordinates not found, cannot apply R_X86_64_JUMP_SLOT @0x3f109e12c0 (0x11f586) in /tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/lib/libQt6Gui.so.6
Look for eglBindAPI in loaded elfs
Warning, function eglBindAPI not found in lib libGL.so.1
Error: Symbol FT_Set_Named_Instance not found, cannot apply R_X86_64_JUMP_SLOT @0x3f109e1660 (0x11fcc6) in /tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/Qt/lib/libQt6Gui.so.6
Error: relocating Plt symbols in elf libQt6Gui.so.6
Error initializing needed lib libgcc_s.so.1
Error loading one of needed lib
Error initializing needed lib /tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/QtGui.abi3.so
Traceback (most recent call last):
  File "/tmp/.mount_ProtonDYTwRL/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_ProtonDYTwRL/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/pupgui2/__main__.py", line 1, in <module>
    from pupgui2.pupgui2 import main
  File "/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/pupgui2/pupgui2.py", line 10, in <module>
    from PySide6.QtGui import QIcon, QKeyEvent, QKeySequence, QShortcut
ImportError: Cannot dlopen("/tmp/.mount_ProtonDYTwRL/usr/local/lib/python3.10/dist-packages/PySide6/QtGui.abi3.so"/0x61e1cf20, 2)

FillBlock triggered a segfault at 0x3f0902cdc0 from 0x350bafe4
FillBlock at 0x3f0902cdc0 triggered a segfault, canceling
FillBlock triggered a segfault at 0x3f0902cdc0 from 0x350bafe4
FillBlock at 0x3f0902cdc0 triggered a segfault, canceling
6266|SIGSEGV @0x350631c8 (???(/tmp/.mount_ProtonDYTwRL/usr/bin/python3+0x8631c8)) (x64pc=0x3f0902cdc0/"???", rsp=0x7f9b83ba38, stack=0x7f9b040000:0x7f9b840000 own=(nil) fp=0x7f9b83ba5f), for accessing 0x3f0902cdc0 (code=1/prot=87), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x0000000061ab9d60 RSP-0x18:0x0000007f9b83bab0 RSP-0x10:0x0000003f040273bd RSP-0x08:0x0000000000000001
RSP+0x00:0x0000003f080e0d31 RSP+0x08:0x00000000602c01f0 RSP+0x10:0x00000001005a0d20 RSP+0x18:0x00000000601ef100
RAX:0x0000000000000000 RCX:0x0000000000000001 RDX:0x0000000061ab9d60 RBX:0x0000000000000001 
RSP:0x0000007f9b83ba38 RBP:0x0000007f9b83ba5f RSI:0x0000000035b2cd20 RDI:0x0000000000000000 
 R8:0x00000001001272a0  R9:0x00000001001589c0 R10:0x0000000060310000 R11:0x0000000100573b00 
R12:0x000000006054cf90 R13:0x000000010039ac4c R14:0x0000000061a9eab0 R15:0x00000001005e2418 
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b FS:0x0043 GS:0x0053 
Segmentation fault`

**Comment by LukeShortCloud** [comment]
@FoxbitDreamtail is this still an issue with the latest Box64?

**Comment by FoxbitDreamtail** [comment]
> [@FoxbitDreamtail](https://github.com/FoxbitDreamtail) is this still an issue with the latest Box64?

I havn't tried it in a long while, I will try it and get back to you.

**Comment by FoxbitDreamtail** [comment]
so, I discovered a new issue but it isn't an issue with Box86/64... it has to do with ProtonUp-Qt expecting Python 3.10 and getting Python 3.11... is there a quick way to fix that?

also, kindof important info, I switched back to RpiOS and am kinda too lazy to switch back to mx linux as that would be a whole system reinstall just to test something, especially as the pi5 is(most of the time) just being used as a wifi-to-ethernet adapter that just so happens to be able to host a singleplayer Minecraft server.
