### ISSUE TITLE
RPCS3 - missing symbols

### ISSUE THREAD

**Issue by Heasterian** [ptitSeb/box64#28]
RPCS3 crashes with message below.

```
Error: Global Symbol _ZTHN2fs11g_tls_errorE not found, cannot apply R_X86_64_GLOB_DAT @0x337a948 ((nil)) in /home/heasterian/Downloads/squashfs-root/usr/bin/rpcs3
Error: Global Symbol _ZTHN10cpu_thread17g_tls_this_threadE not found, cannot apply R_X86_64_GLOB_DAT @0x337a9b8 ((nil)) in /home/heasterian/Downloads/squashfs-root/usr/bin/rpcs3
Error: Global Symbol _ZTHN11thread_ctrl17g_tls_this_threadE not found, cannot apply R_X86_64_GLOB_DAT @0x337a9c0 ((nil)) in /home/heasterian/Downloads/squashfs-root/usr/bin/rpcs3
Error: Global Symbol _ZTH16g_tls_log_prefixB5cxx11 not found, cannot apply R_X86_64_GLOB_DAT @0x337a9c8 ((nil)) in /home/heasterian/Downloads/squashfs-root/usr/bin/rpcs3
Error: Global Symbol _ZTHN2vm12g_tls_lockedE not found, cannot apply R_X86_64_GLOB_DAT @0x337a9d0 ((nil)) in /home/heasterian/Downloads/squashfs-root/usr/bin/rpcs3
Error: Global Symbol _ZTHN3idm4g_idE not found, cannot apply R_X86_64_GLOB_DAT @0x337a9d8 ((nil)) in /home/heasterian/Downloads/squashfs-root/usr/bin/rpcs3
Error: Global Symbol _ZTH17g_tls_log_control not found, cannot apply R_X86_64_GLOB_DAT @0x337a9f0 ((nil)) in /home/heasterian/Downloads/squashfs-root/usr/bin/rpcs3
Error: Global Symbol _ZTHN3rsx8overlays14user_interface12g_thread_bitE not found, cannot apply R_X86_64_GLOB_DAT @0x337a9f8 ((nil)) in /home/heasterian/Downloads/squashfs-root/usr/bin/rpcs3
Error: Global Symbol __morestack not found, cannot apply R_X86_64_GLOB_DAT @0x337b730 ((nil)) in /home/heasterian/Downloads/squashfs-root/usr/bin/rpcs3
22598|SIGSEGV @0x648cbd1c (???(/usr/local/bin/box64/0x648cbd1c)) (x64pc=0x1/???:"???", rsp=0x7f92f72688, stack=0x7f92774000:0x7f92f74000 own=(nil) fp=0x69be00), for accessing (nil) (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=0x1
Segmentation fault (core dumped)
```

**Comment by Heasterian** [comment]
It went a bit further.

```
Error: Global Symbol __morestack not found, cannot apply R_X86_64_GLOB_DAT @0x337b730 ((nil)) in /home/heasterian/Downloads/squashfs-root/usr/bin/rpcs3
Debugger: 0
Warning, CPUID command 80000007 unsupported (ECX=00000000)
Error: PltResolver: Symbol __cxa_thread_atexit_impl(ver 49: __cxa_thread_atexit_impl@GLIBC_2.18) not found, cannot apply R_X86_64_JUMP_SLOT 0x7fa57d8ab0 (0x7fa56e4566) in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Error: PltResolver: Symbol __cxa_thread_atexit_impl(ver 49: __cxa_thread_atexit_impl@GLIBC_2.18) not found, cannot apply R_X86_64_JUMP_SLOT 0x7fa57d8ab0 (0x7fa56e4566) in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
11615|SIGSEGV @0x648cd2dc (???(/usr/local/bin/box64/0x648cd2dc)) (x64pc=0x1201/???:"???", rsp=0x7faa936420, stack=0x7faa138000:0x7faa938000 own=(nil) fp=0x1), for accessing 0x1200 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=0x6a8ca0
11615|0x6a3ade: Unimplemented Opcode (00) 64 0F B6 04 25 F5 D5 FF FF 88 44 24 0F 64 C6
11615|Double SIGSEGV (code=1, pc=0x648cd2dc, addr=0x1200)!
```

**Comment by Heasterian** [comment]
```
Error: PltResolver: Symbol xcb_xfixes_query_version(ver 0: xcb_xfixes_query_version) not found, cannot apply R_X86_64_JUMP_SLOT 0x7f00680988 (0x7f003685b6) in /home/heasterian/Downloads/squashfs-root/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
Library libQt5XcbQpa.so.5 (0x837f8640) needs 0x837f39b0, but it was not found. Ignoring.
Library libQt5Gui.so.5 (0x7cf40ae0) needs 0x837f39b0, but it was not found. Ignoring.
Library libQt5Core.so.5 (0x7d0a1280) needs 0x837f39b0, but it was not found. Ignoring.
Library libc.so.6 (0x7d282dd0) needs 0x837f39b0, but it was not found. Ignoring.
Library libstdc++.so.6 (0x7d1b5a70) needs 0x837f39b0, but it was not found. Ignoring.
30532|SIGSEGV @0x648cd66c (???(/usr/local/bin/box64/0x648cd66c)) (x64pc=0x1201/???:"???", rsp=0x85e9dfe0, stack=0x7f927c6000:0x7f92fc6000 own=(nil) fp=0x7f0067ce38), for accessing 0x1200 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=0x6a8ca0
Error: PltResolver: Symbol memcmp(ver 42: memcmp@GLIBC_2.2.5) not found, cannot apply R_X86_64_JUMP_SLOT 0x7f8de673c8 (0x7f8dd73796) in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
30532|Double SIGSEGV (code=1, pc=0x648cd66c, addr=0x1200)!
```

**Comment by Heasterian** [comment]
Now it stops on symbol 
```
Error: PltResolver: Symbol xcb_xfixes_query_version(ver 0: xcb_xfixes_query_version) not found, cannot apply R_X86_64_JUMP_SLOT 0x7ef35f8988 (0x7ef32e05b6) in /media/heasterian/6ccd3ef5-2fe5-4768-8750-05dc9bb6372a/squashfs-root/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5```

**Comment by Heasterian** [comment]
Looks like we need some more versions.

```
Error: PltResolver: Symbol xcb_shape_query_version(ver 0: xcb_shape_query_version) not found, cannot apply R_X86_64_JUMP_SLOT 0x7f03df9098 (0x7f03ae03d6) in /media/heasterian/6ccd3ef5-2fe5-4768-8750-05dc9bb6372a/squashfs-root/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
```

**Comment by alexvorxx** [comment]
On the latest versions of box64 there are trace/breakpoint trap:

...
Using native(wrapped) libharfbuzz.so.0
Warning: Global Symbol _ZTH20g_tls_serialize_name not found, cannot apply R_X86_64_GLOB_DAT @0x3a99218 ((nil)) in /usr/bin/rpcs3
Warning: Global Symbol _ZTHN2fs11g_tls_errorE not found, cannot apply R_X86_64_GLOB_DAT @0x3a99310 ((nil)) in /usr/bin/rpcs3
Warning: Global Symbol _ZTHN11thread_ctrl17g_tls_this_threadE not found, cannot apply R_X86_64_GLOB_DAT @0x3a993a0 ((nil)) in /usr/bin/rpcs3
Warning: Global Symbol _ZTHN10cpu_thread17g_tls_this_threadE not found, cannot apply R_X86_64_GLOB_DAT @0x3a993b0 ((nil)) in /usr/bin/rpcs3
Warning: Global Symbol _ZTH16g_tls_log_prefixB5cxx11 not found, cannot apply R_X86_64_GLOB_DAT @0x3a993b8 ((nil)) in /usr/bin/rpcs3
Warning: Global Symbol _ZTHN10id_manager4g_idE not found, cannot apply R_X86_64_GLOB_DAT @0x3a993c0 ((nil)) in /usr/bin/rpcs3
Warning: Global Symbol _ZTHN2vm12g_tls_lockedE not found, cannot apply R_X86_64_GLOB_DAT @0x3a993e0 ((nil)) in /usr/bin/rpcs3
Warning: Global Symbol _ZTHN7lv2_obj25g_postpone_notify_barrierE not found, cannot apply R_X86_64_GLOB_DAT @0x3a993e8 ((nil)) in /usr/bin/rpcs3
Warning: Global Symbol _ZTHN7lv2_obj11g_to_notifyE not found, cannot apply R_X86_64_GLOB_DAT @0x3a993f0 ((nil)) in /usr/bin/rpcs3
Warning: Global Symbol _ZTH17g_tls_log_control not found, cannot apply R_X86_64_GLOB_DAT @0x3a993f8 ((nil)) in /usr/bin/rpcs3
Warning: Global Symbol __morestack not found, cannot apply R_X86_64_GLOB_DAT @0x3a9a858 ((nil)) in /usr/bin/rpcs3
Debugger: 1
Using emulated /usr/plugins/platforms/libqxcb.so
Using emulated /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libX11-xcb.so.1
Using native(wrapped) libxcb-icccm.so.4
Using native(wrapped) libxcb-image.so.0
Using native(wrapped) libxcb-shm.so.0
Using native(wrapped) libxcb-keysyms.so.1
Using native(wrapped) libxcb-randr.so.0
Using native(wrapped) libxcb-render-util.so.0
Using native(wrapped) libxcb-render.so.0
Using native(wrapped) libxcb-shape.so.0
Using native(wrapped) libxcb-sync.so.1
Using native(wrapped) libxcb-xfixes.so.0
Using native(wrapped) libxcb-xinerama.so.0
Using native(wrapped) libxcb-xkb.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libxcb-xinput.so.0
Using native(wrapped) libxcb.so.1
Using native(wrapped) libSM.so.6
Using native(wrapped) libICE.so.6
Using native(wrapped) libxkbcommon-x11.so.0
Using native(wrapped) libxkbcommon.so.0
Using native(wrapped) libXcursor.so.1
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Using emulated /usr/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
Waiting for gdb (pid 6311)...
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 6311
[New LWP 6320]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
0x00000072bc211924 in __GI___clock_nanosleep (clock_id=<optimized out>, clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7ffe11bd48, rem=rem@entry=0x0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
78      ../sysdeps/unix/sysv/linux/clock_nanosleep.c: No such file or directory.
(gdb) bt
#0  0x00000072bc211924 in __GI___clock_nanosleep (
    clock_id=<optimized out>, clock_id@entry=0,
    flags=flags@entry=0, req=req@entry=0x7ffe11bd48,
    rem=rem@entry=0x0)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
#1  0x00000072bc216aec in __GI___nanosleep (
    req=req@entry=0x7ffe11bd48, rem=rem@entry=0x0)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x00000072bc23f2f4 in usleep (
    useconds=<optimized out>)
    at ../sysdeps/posix/usleep.c:31
#3  0x00000000349f61f4 in ?? ()
#4  <signal handler called>
#5  0x00000072acfc1e20 in ?? ()
#6  0x00000000350dd000 in fwrite@got[plt] ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by rajdakin** [comment]
Is this fixed now?

**Comment by LukeShortCloud** [comment]
According to the latest release of Winlator, RPCS3 is now working with the latest build of Box64.

https://github.com/wb64dev/winlator/releases/tag/v8.5.5

Closing as resolved.
