### ISSUE TITLE
runtime.semrelease: fatal error: fault [signal 0xc0000005 code=0x0 addr=0x60140eea3f0 pc=0x14004bde2]

### ISSUE THREAD

**Issue by kmlebedev** [ptitSeb/box64#430]
### What version of Go are you using (`go version`)?

<pre>
$ root@orangepi-rk3399:/usr/local/src/txmlconnector# go version
go version go1.19.2 linux/arm64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

on arm64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/usr/local/src/txmlconnector/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build552478422=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
git clone https://github.com/kmlebedev/txmlconnector.git
cd txmlconnector
CGO_ENABLED=1 CC="x86_64-w64-mingw32-gcc" CXX="x86_64-w64-mingw32-g++" GOOS=windows GOARCH=amd64 go build -ldflags "-extldflags -static -s -w" -o bin/server.exe main.go
box64 /usr/local/wine/bin/wine64 bin/server.exe
</pre>

### What did you expect to see?

on intel MacOSX
<pre>
make server
CGO_ENABLED=1 CC="x86_64-w64-mingw32-gcc" CXX="x86_64-w64-mingw32-g++" GOOS=windows GOARCH=amd64 go build -ldflags "-extldflags -static -s -w" -o bin/server.exe main.go
mkdir -p logs
wine64 bin/server.exe
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
0024:fixme:powrprof:PowerRegisterSuspendResumeNotification (0x00000002,000000000021FBC0,000000000021FBA8) stub!
time="2022-10-24T14:40:44+05:00" level=info msg="Initialize module: txmlconnector64-6.19.2.21.21.dll"
InitCrashHandler: Z:\Users\kmlebedev\go\src\txmlconnector\bin\server-221024-144047.mdmp
time="2022-10-24T14:40:47+05:00" level=info msg="Server running ..."
0110:fixme:ver:GetCurrentPackageId (00000000274EFE10 0000000000000000): stub
time="2022-10-24T14:40:47+05:00" level=info msg="Press CRTL+C to stop the server..."
^C^Ctime="2022-10-24T14:44:24+05:00" level=info msg="\r Ctrl+C pressed in Terminal"
</pre>

### What did you see instead?

<pre>
box64 /usr/local/wine/bin/wine64 bin/server.exe
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
40976|SIGSEGV @0xffff78642e04 (???(0xffff78642e04)) (x64pc=0x14004bdc2/???:"???", rsp=0xc00007b288, stack=0xffff8001d000:0xffff8081d000 own=(nil) fp=0xc00007b2c8), for accessing 0x601408af6b0 (code=1/prot=0), db=0xffff78aa9248(0xffff78642cb0:0xffff78642eac/0x14004bd60:0x14004bdf4/???:clean, hash:e7d701f9/e7d701f9) handler=0x10004d020
RAX:0x4f8dc4e73c2ce655 RCX:0x0000000000000000 RDX:0x00000001408990e0 RBX:0x0000000000000000
RSP:0x000000c00007b288 RBP:0x000000c00007b2c8 RSI:0x00000600000165c0 RDI:0x000000c000004c18
 R8:0x00000601408af6b0  R9:0x0000000000000000 R10:0x000000010008b6b0 R11:0x0000000000000020
R12:0x0000000000000000 R13:0x0000000000000000 R14:0x000000c00003c000 R15:0x0000000002030000
RSP-0x20:0x0000000140063f3b RSP-0x18:0x000000007b60bbd0 RSP-0x10:0x000000c00007b290 RSP-0x08:0x0000000000000003
RSP+0x00:0x0000000000000000 RSP+0x08:0x0000000000000104 RSP+0x10:0x0000000000000000 RSP+0x18:0x0000000000000000
unexpected fault address 0x601408af6b0
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x601408af6b0 pc=0x14004bdc2]

goroutine 1 [running, locked to thread]:
runtime.throw({0x140535fbe?, 0x0?})
        /usr/local/go/src/runtime/panic.go:1047 +0x65 fp=0xc00007b240 sp=0xc00007b210 pc=0x140039cc5
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_windows.go:261 +0x125 fp=0xc00007b288 sp=0xc00007b240 pc=0x14004d165
runtime.semrelease1(0x104?, 0x4?, 0xc00002a720?)
        /usr/local/go/src/runtime/sema.go:172 +0x62 fp=0xc00007b2d8 sp=0xc00007b288 pc=0x14004bdc2
runtime.semrelease(...)
        /usr/local/go/src/runtime/sema.go:162
internal/poll.runtime_Semrelease(0x0?)
        /usr/local/go/src/runtime/sema.go:82 +0x1d fp=0xc00007b300 sp=0xc00007b2d8 pc=0x140062d3d
internal/poll.(*FD).destroy(0xc000004a00)
        /usr/local/go/src/internal/poll/fd_windows.go:380 +0xc5 fp=0xc00007b328 sp=0xc00007b300 pc=0x1400d3505
internal/poll.(*FD).decref(0xc00007b2d0?)
        /usr/local/go/src/internal/poll/fd_mutex.go:213 +0x53 fp=0xc00007b348 sp=0xc00007b328 pc=0x1400d1113
internal/poll.(*FD).Close(0xc000004a00)
        /usr/local/go/src/internal/poll/fd_windows.go:395 +0x69 fp=0xc00007b378 sp=0xc00007b348 pc=0x1400d35c9
os.(*file).close(0xc000004a00)
        /usr/local/go/src/os/file_windows.go:197 +0x56 fp=0xc00007b3c8 sp=0xc00007b378 pc=0x1400e03d6
os.(*File).Close(0x1?)
        /usr/local/go/src/os/file_posix.go:25 +0x25 fp=0xc00007b3e0 sp=0xc00007b3c8 pc=0x1400defa5
google.golang.org/protobuf/internal/detrand.binaryHash.func1()
        /Users/tochka/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/detrand/rand.go:50 +0x26 fp=0xc00007b3f8 sp=0xc00007b3e0 pc=0x140117606
google.golang.org/protobuf/internal/detrand.binaryHash()
        /Users/tochka/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/detrand/rand.go:68 +0x25c fp=0xc00007b4c0 sp=0xc00007b3f8 pc=0x14011759c
google.golang.org/protobuf/internal/detrand.init()
        /Users/tochka/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/detrand/rand.go:38 +0x17 fp=0xc00007b4d0 sp=0xc00007b4c0 pc=0x140117657
runtime.doInit(0x14040bc80)
        /usr/local/go/src/runtime/proc.go:6321 +0x12d fp=0xc00007b600 sp=0xc00007b4d0 pc=0x140048f6d
runtime.doInit(0x14040bd00)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc00007b730 sp=0xc00007b600 pc=0x140048eb1
runtime.doInit(0x14040bc40)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc00007b860 sp=0xc00007b730 pc=0x140048eb1
runtime.doInit(0x14040bcc0)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc00007b990 sp=0xc00007b860 pc=0x140048eb1
runtime.doInit(0x14040ff80)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc00007bac0 sp=0xc00007b990 pc=0x140048eb1
runtime.doInit(0x140411bc0)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc00007bbf0 sp=0xc00007bac0 pc=0x140048eb1
runtime.doInit(0x14040f580)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc00007bd20 sp=0xc00007bbf0 pc=0x140048eb1
runtime.doInit(0x140410420)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc00007be50 sp=0xc00007bd20 pc=0x140048eb1
runtime.doInit(0x140409b40)
        /usr/local/go/src/runtime/proc.go:6298 +0x71 fp=0xc00007bf80 sp=0xc00007be50 pc=0x140048eb1
runtime.main()
        /usr/local/go/src/runtime/proc.go:233 +0x1bf fp=0xc00007bfe0 sp=0xc00007bf80 pc=0x14003c3bf
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00007bfe8 sp=0xc00007bfe0 pc=0x140067501

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00003ffb0 sp=0xc00003ff90 pc=0x14003c796
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:302 +0xb1 fp=0xc00003ffe0 sp=0xc00003ffb0 pc=0x14003c631
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00003ffe8 sp=0xc00003ffe0 pc=0x140067501
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000041f90 sp=0xc000041f70 pc=0x14003c796
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc000041fc8 sp=0xc000041f90 pc=0x1400269ce
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc000041fe0 sp=0xc000041fc8 pc=0x14001b566
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000041fe8 sp=0xc000041fe0 pc=0x140067501
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000028070?, 0x1405f9eb0?, 0x1?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000051f70 sp=0xc000051f50 pc=0x14003c796
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x140895bc0)
        /usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000051fa0 sp=0xc000051f70 pc=0x140024a53
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc000051fc8 sp=0xc000051fa0 pc=0x140025045
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000051fe0 sp=0xc000051fc8 pc=0x14001b506
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000051fe8 sp=0xc000051fe0 pc=0x140067501
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x1408962e0?, 0xc00003cea0?, 0x0?, 0x0?, 0xc000043f70?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000043e28 sp=0xc000043e08 pc=0x14003c796
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:180 +0x10f fp=0xc000043fe0 sp=0xc000043e28 pc=0x14001a66f
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000043fe8 sp=0xc000043fe0 pc=0x140067501
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:157 +0x45
</pre>

https://github.com/kmlebedev/txmlconnector/issues/9
https://github.com/golang/go/issues/56393

**Comment by kmlebedev** [comment]
@ptitSeb Any idea what can be done about this and on whose side the problem is?

**Comment by kmlebedev** [comment]
> BOX86_DYNAREC=0

Yes. wine not running
```
export BOX86_DYNAREC=0 && rm -rf ~/.wine && box64 /usr/local/wine/bin/wine64 main.exe
Dynarec is off
Box64 with Dynarec v0.1.9 2e9bc93 built on Oct 24 2022 20:06:24
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 29 Env var
Looking for /usr/local/wine/bin/wine64
argv[1]="main.exe"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/local/wine/bin/../lib64/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Dynarec is off
Box64 with Dynarec v0.1.9 2e9bc93 built on Oct 24 2022 20:06:24
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 30 Env var
Looking for /usr/local/wine/bin/wine64
argv[1]="main.exe"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/local/wine/bin/../lib64/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
wine: created the configuration directory '/root/.wine'
Dynarec is off
Box64 with Dynarec v0.1.9 2e9bc93 built on Oct 24 2022 20:06:24
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 30 Env var
Looking for /usr/local/wine/bin/wineserver
Rename process to "wineserver"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/local/wine/lib64/wine/../libwine.so.1
002c:err:virtual:virtual_setup_exception nested exception on signal stack in thread 002c addr 0x10004ce07 stack 0x7fffffd9f580 (0x1d0000-0x1d2000-0x3d0000)
Dynarec is off
Box64 with Dynarec v0.1.9 2e9bc93 built on Oct 24 2022 20:06:24
BOX64: Wine64 detected, WINEPRELOADRESERVE="000000000-000000000"
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 32 Env var
Looking for /usr/local/wine/bin/wine64
argv[1]="C:\windows\system32\conhost.exe"
argv[2]="--unix"
argv[3]="--width"
argv[4]="224"
argv[5]="--height"
argv[6]="72"
argv[7]="--server"
argv[8]="0x10"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/local/wine/bin/../lib64/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using emulated /usr/local/wine/lib64/wine/../libwine.so.1
0024:err:virtual:virtual_setup_exception nested exception on signal stack in thread 0024 addr 0x10004ce07 stack 0x7fffffd9f580 (0x1d0000-0x1d2000-0x3d0000)
root@orangepi-rk3399:/tmp# Using emulated /usr/local/wine/lib64/wine/ucrtbase.so
Using emulated /usr/local/wine/lib64/wine/gdi32.so
Using emulated /usr/local/wine/lib64/wine/user32.so
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
0034:err:virtual:virtual_setup_exception nested exception on signal stack in thread 0034 addr 0x10004ce07 stack 0x7fffffd9f580 (0x1d0000-0x1d2000-0x3d0000)

```

**Comment by fankunyang** [comment]
Hi all, 

I have the similar problem with Windows golang program. The same error patterns as below. I found rollback the BOX64 to tag "v0.2.0" can workaround this problem. 

`
pi@raspberrypi:~ $ wine64 Fanuc/main.exe 192.168.50.87 8391 
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 22 entries
Box64 with Dynarec v0.2.3 38cf6120 built on Mar 31 2023 04:41:10
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 49 Env var
Looking for /usr/local/bin/wine64
argv[1]="Fanuc/main.exe"
argv[2]="192.168.50.87"
argv[3]="8391"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/bin/../lib64/wine/x86_64-unix/ntdll.so
Using native(wrapped) libunwind.so.8
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 22 entries
Box64 with Dynarec v0.2.3 38cf6120 built on Mar 31 2023 04:41:10
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 50 Env var
Looking for /home/pi/wine/bin/wine64
argv[1]="Fanuc/main.exe"
argv[2]="192.168.50.87"
argv[3]="8391"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/bin/../lib64/wine/x86_64-unix/ntdll.so
Using native(wrapped) libunwind.so.8
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 22 entries
Box64 with Dynarec v0.2.3 38cf6120 built on Mar 31 2023 04:41:10
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 50 Env var
Looking for /home/pi/wine/bin/wineserver
Rename process to "wineserver"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/lib64/wine/x86_64-unix/libwine.so.1
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 22 entries
Box64 with Dynarec v0.2.3 38cf6120 built on Mar 31 2023 04:41:10
BOX64: Wine64 detected, WINEPRELOADRESERVE="000400000-0004a8000"
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 52 Env var
Looking for /home/pi/wine/bin/wine64
argv[1]="C:\windows\system32\conhost.exe"
argv[2]="--unix"
argv[3]="--width"
argv[4]="80"
argv[5]="--height"
argv[6]="24"
argv[7]="--server"
argv[8]="0x10"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/bin/../lib64/wine/x86_64-unix/ntdll.so
Using native(wrapped) libunwind.so.8
Using emulated /home/pi/wine/lib64/wine/x86_64-unix/libwine.so.1
Using emulated /home/pi/wine/lib64/wine/x86_64-unix/win32u.so
Using native(wrapped) libm.so.6
Using emulated /home/pi/wine/lib64/wine/x86_64-unix/win32u.so
Using native(wrapped) libm.so.6
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using emulated /home/pi/wine/lib64/wine/x86_64-unix/ws2_32.so
0024:fixme:process:SetProcessPriorityBoost (FFFFFFFFFFFFFFFF,1): stub
0024:fixme:powrprof:PowerRegisterSuspendResumeNotification (0x00000002,00000000002DFBB0,00000000002DFB98) stub!
fatal error: slice bounds out of range

goroutine 1 [running, locked to thread]:
runtime.throw({0x87dd57?, 0x75fac0?})
        C:/Program Files/Go/src/runtime/panic.go:1047 +0x65 fp=0x2783f528 sp=0x2
783f4f8 pc=0x438dc5
runtime.panicCheck1(0x2783f5f8?, {0x87dd57, 0x19})
        C:/Program Files/Go/src/runtime/panic.go:57 +0x87 fp=0x2783f548 sp=0x278
3f528 pc=0x436847
runtime.goPanicSliceAlen(0xd, 0x20)
        C:/Program Files/Go/src/runtime/panic.go:126 +0x34 fp=0x2783f588 sp=0x27
83f548 pc=0x436a74
runtime.stringtoslicerune(0x2783f618, {0x2783f5f8, 0xd})
        C:/Program Files/Go/src/runtime/string.go:195 +0x179 fp=0x2783f5d0 sp=0x
2783f588 pc=0x450b59
syscall.UTF16FromString({0x8776ab, 0xc})
        C:/Program Files/Go/src/syscall/syscall_windows.go:46 +0xc5 fp=0x2783f6a
8 sp=0x2783f5d0 pc=0x475445
syscall.UTF16PtrFromString(...)
        C:/Program Files/Go/src/syscall/syscall_windows.go:96
syscall.LoadDLL({0x8776ab, 0xc})
        C:/Program Files/Go/src/syscall/dll_windows.go:85 +0x3b fp=0x2783f750 sp
=0x2783f6a8 pc=0x47459b
syscall.(*LazyDLL).Load(0x2788e080)
        C:/Program Files/Go/src/syscall/dll_windows.go:218 +0xa5 fp=0x2783f7a0 s
p=0x2783f750 pc=0x474ca5
syscall.(*LazyProc).Find(0x2788af00)
        C:/Program Files/Go/src/syscall/dll_windows.go:273 +0xa5 fp=0x2783f7f8 s
p=0x2783f7a0 pc=0x474e65
syscall.(*LazyProc).mustFind(...)
        C:/Program Files/Go/src/syscall/dll_windows.go:291
syscall.(*LazyProc).Addr(...)
        C:/Program Files/Go/src/syscall/dll_windows.go:300
syscall.GetStdHandle(0x83fcc0?)
        C:/Program Files/Go/src/syscall/zsyscall_windows.go:861 +0x32 fp=0x2783f
848 sp=0x2783f7f8 pc=0x4787d2
syscall.getStdHandle(...)
        C:/Program Files/Go/src/syscall/syscall_windows.go:495
syscall.init()
        C:/Program Files/Go/src/syscall/syscall_windows.go:489 +0x2a0b fp=0x2783
fd20 sp=0x2783f848 pc=0x47d6cb
runtime.doInit(0x759900)
        C:/Program Files/Go/src/runtime/proc.go:6321 +0x12d fp=0x2783fe50 sp=0x2
783fd20 pc=0x44806d
runtime.doInit(0x75a360)
        C:/Program Files/Go/src/runtime/proc.go:6298 +0x71 fp=0x2783ff80 sp=0x27
83fe50 pc=0x447fb1
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:233 +0x1bf fp=0x2783ffe0 sp=0x27
83ff80 pc=0x43b4bf
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0x2783ffe8 sp=0
x2783ffe0 pc=0x466ae1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:363 +0xd6 fp=0x2783bfb0 sp=0x278
3bf90 pc=0x43b896
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:369
runtime.forcegchelper()
        C:/Program Files/Go/src/runtime/proc.go:302 +0xb1 fp=0x2783bfe0 sp=0x278
3bfb0 pc=0x43b731
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0x2783bfe8 sp=0
x2783bfe0 pc=0x466ae1
created by runtime.init.6
        C:/Program Files/Go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:363 +0xd6 fp=0x2783df90 sp=0x278
3df70 pc=0x43b896
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        C:/Program Files/Go/src/runtime/mgcsweep.go:278 +0x8e fp=0x2783dfc8 sp=0
x2783df90 pc=0x425a8e
runtime.gcenable.func1()
        C:/Program Files/Go/src/runtime/mgc.go:178 +0x26 fp=0x2783dfe0 sp=0x2783
dfc8 pc=0x41a626
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0x2783dfe8 sp=0
x2783dfe0 pc=0x466ae1
created by runtime.gcenable
        C:/Program Files/Go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x2781e070?, 0x91f348?, 0x1?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:363 +0xd6 fp=0x2784bf70 sp=0x278
4bf50 pc=0x43b896
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0xb253e0)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:389 +0x53 fp=0x2784bfa0 s
p=0x2784bf70 pc=0x423b13
runtime.bgscavenge(0x0?)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:617 +0x45 fp=0x2784bfc8 s
p=0x2784bfa0 pc=0x424105
runtime.gcenable.func2()
        C:/Program Files/Go/src/runtime/mgc.go:179 +0x26 fp=0x2784bfe0 sp=0x2784
bfc8 pc=0x41a5c6
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0x2784bfe8 sp=0
x2784bfe0 pc=0x466ae1

'

**Comment by fankunyang** [comment]
After using the version BOX64 v0.2.0, the golang windows program can run, but it still happened the Segfault error after 10 minutes. The same problem in x86 platform with the same version WINE64 in Debian 11 doesn't happened. 
`[GIN] 2023/03/31 - 05:27:41 | 200 |      5.8345ms |  192.168.50.206 | GET      "/api"
0110:err:seh:call_stack_handlers invalid frame 0000000027A89410 (0000000028EA2000-00000000290A0000)
0110:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
`

**Comment by LukeShortCloud** [comment]
Just to note, there are still known issues around running Go programs with Box64.
