### ISSUE TITLE
WebFrameMain Issue with Slack

### ISSUE THREAD

**Issue by theironrobin** [ptitSeb/box64#538]
Version: Latest box64-git 
Slack version: Latest x86_64 beta release
Steps to reproduce:
- Run slack, login buttons works
- Choose a workspace in browser, click Open in Slack
outcome: Slack window stays a blank purple
console output:
```
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:169:631)
    at g.send (node:electron/js2c/browser_init:165:2156)
    at /usr/lib/slack/resources/app.asar/dist/main.bundle.js:262:6544
    at Array.forEach (<anonymous>)
    at /usr/lib/slack/resources/app.asar/dist/main.bundle.js:262:6522
    at /usr/lib/slack/resources/app.asar/dist/main.bundle.js:143:7146
    at /usr/lib/slack/resources/app.asar/dist/main.bundle.js:130:22082
    at /usr/lib/slack/resources/app.asar/dist/main.bundle.js:263:922
    at dispatch (/usr/lib/slack/resources/app.asar/dist/main.bundle.js:130:18986)
    at Object.next (/usr/lib/slack/resources/app.asar/dist/main.bundle.js:318:87665)
```

**Comment by LukeShortCloud** [comment]
@theironrobin is this still an issue with the latest version of Box64?
