### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by Painadath** [ptitSeb/box64#71]
Error
```
Error: Global Symbol collector_func_load not found, cannot apply R_X86_64_GLOB_DAT @0x7f90305f88 ((nil)) in /home/pi/android-studio/jre/lib/server/libjvm.so
Error: Symbol posix_fallocate not found, cannot apply R_X86_64_JUMP_SLOT @0x7f90306128 (0x27aed6) in /home/pi/android-studio/jre/lib/server/libjvm.so
Error: Symbol vfork not found, cannot apply R_X86_64_JUMP_SLOT @0x7f90306220 (0x27b0c6) in /home/pi/android-studio/jre/lib/server/libjvm.so
Warning: Weak Symbol __gmon_start__ not found, cannot apply R_X86_64_JUMP_SLOT @0x7f90306230 (0x27b0e6)
Error: Symbol getutxent not found, cannot apply R_X86_64_JUMP_SLOT @0x7f903063f0 (0x27b466) in /home/pi/android-studio/jre/lib/server/libjvm.so
Warning: Weak Symbol collector_func_load not found, cannot apply R_X86_64_JUMP_SLOT @0x7f90306658 (0x27b936)
Error: Symbol setutxent not found, cannot apply R_X86_64_JUMP_SLOT @0x7f90306728 (0x27bad6) in /home/pi/android-studio/jre/lib/server/libjvm.so
Error: relocating Plt symbols in elf libjvm.so
Error initializing needed lib libjvm.so
Warning: Cannot dlopen("/home/pi/android-studio/jre/lib/server/libjvm.so"/0x7f91343980, 102)
Error: dl failure on line 598
Error: failed /home/pi/android-studio/jre/lib/server/libjvm.so, because Cannot dlopen("/home/pi/android-studio/jre/lib/server/libjvm.so"/0x7f91343980, 102)
```

**Comment by hex007** [comment]
Really? You want to run Android Studio on pi ?

**Comment by Painadath** [comment]
@hex007 I want to run the emulator not android studio any idea?

**Comment by ptitSeb** [comment]
Box64 doesn't support Java for now.

**Comment by hex007** [comment]
Use pi things for android on pi. Thrrr are projects that support full android os on it

**Comment by Painadath** [comment]
But is there a working emulator for raspberry pi?
And I hate using android as os on raspberry pi

**Comment by USMP-lancer** [comment]
> Box64 doesn't support Java for now.

so far the only issue i seen when trying to use the jre to run an app is it cant see the jar file, this is likely due to how your emulating it though

**Comment by rajdakin** [comment]
Is this fixed now?

**Comment by OpenSauce04** [comment]
I just tried this, and I'm running into a different error than the one the author of this issue brought up. Java seems to be working correctly, but this issue occurs instead:

<details>
<summary>
Android Studio + Box64 run log
</summary>

```
Internal error

java.lang.InternalError: Unable to load native GTK libraries
        at java.desktop/com.sun.java.swing.plaf.gtk.GTKLookAndFeel.initialize(Unknown Source)
        at com.intellij.ide.ui.laf.LookAndFeelThemeAdapterKt.createBaseLaF(LookAndFeelThemeAdapter.kt:307)
        at com.intellij.platform.ide.bootstrap.UiKt$initLafAndScale$baseLaF$1.invokeSuspend(ui.kt:95)
        at com.intellij.platform.ide.bootstrap.UiKt$initLafAndScale$baseLaF$1.invoke(ui.kt)
        at com.intellij.platform.ide.bootstrap.UiKt$initLafAndScale$baseLaF$1.invoke(ui.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span(tracer.kt:56)
        at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span$default(tracer.kt:48)
        at com.intellij.platform.ide.bootstrap.UiKt.initLafAndScale(ui.kt:95)
        at com.intellij.platform.ide.bootstrap.UiKt.access$initLafAndScale(ui.kt:1)
        at com.intellij.platform.ide.bootstrap.UiKt$initLafAndScale$1.invokeSuspend(ui.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:318)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```
</details>

If it matters, I am using a locally compiled build of Box64 with Box32 enabed from commit 198eea49a83909209d203eea2e718112cca5dc48

**Comment by ptitSeb** [comment]
> I just tried this, and I'm running into a different error than the one the author of this issue brought up. Java seems to be working correctly, but this issue occurs instead with an accompanying Java error box which has the same message:
> 
> Android Studio + Box64 run log
> If it matters, I am using a locally compiled build of Box64 with Box32 enabed from commit [198eea4](https://github.com/ptitSeb/box64/commit/198eea49a83909209d203eea2e718112cca5dc48)

This look like a missing wrapped function of some gtk lib. You might need to run with `BOX64_DLSYM_ERROR=1` to see wich function is missing...

**Comment by OpenSauce04** [comment]
> > I just tried this, and I'm running into a different error than the one the author of this issue brought up. Java seems to be working correctly, but this issue occurs instead with an accompanying Java error box which has the same message:
> > Android Studio + Box64 run log
> > If it matters, I am using a locally compiled build of Box64 with Box32 enabed from commit [198eea4](https://github.com/ptitSeb/box64/commit/198eea49a83909209d203eea2e718112cca5dc48)
> 
> This look like a missing wrapped function of some gtk lib. You might need to run with `BOX64_DLSYM_ERROR=1` to see wich function is missing...

I have no idea what parts of this log may or may not be relevant, so I'll attach the whole thing here:

[android-studio-box64-run-dlsym-error.txt](https://github.com/user-attachments/files/20062477/android-studio-box64-run-dlsym-error.txt)

**Comment by ptitSeb** [comment]
Missing function seems to be `g_string_replace`. I'll add that later.

Also, I think you are not using latest version of box64...

**Comment by OpenSauce04** [comment]
I have re-built from 5d14413b89d7bb78023307fc59d2d9da182554a4 and while the error with `g_string_replace` appears to be gone, the same error except with `g_uuid_string_is_valid` has taken its place.
It may be worth running Android Studio locally to see if there are any additional functions which may be stopping it from loading.

I have produced another log:
[android-studio-box64-run-dlsym-error.txt](https://github.com/user-attachments/files/20100017/android-studio-box64-run-dlsym-error.txt)

**Comment by ptitSeb** [comment]
Ah, some icons looks strange indeed. That is a vry heavy program to emulated, and to debug...

I'll keep it in mind, to check later if I see something.
