### ISSUE TITLE
Missing wrapped function

### ISSUE THREAD

**Issue by LionheartPL** [ptitSeb/box64#769]
Hi guys, I've been getting this error when trying to emulate the Ubuntu 22.04 version of the following application on box64:
https://sensirion.com/products/sensor-evaluation/control-center/

Ive tried installing previous versions that yielded different error messages, but this seemed like the most "promising" one.
Thanks for the support!

box64 ControlCenter
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 25 entries
Box64 with Dynarec v0.2.3 464d868a built on Apr 29 2023 21:39:46
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 47 Env var
Looking for ControlCenter
Rename process to "ControlCenter"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libz.so.1
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 25 entries
Box64 with Dynarec v0.2.3 464d868a built on Apr 29 2023 21:39:46
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 50 Env var
Looking for /home/cypellab/Documents/ControlCenter
Rename process to "ControlCenter"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libz.so.1
Using emulated /tmp/_MEIfKg5rV/libpython3.8.so.1.0
Using native(wrapped) libm.so.6
Using emulated /tmp/_MEIfKg5rV/lib-dynload/_struct.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/zlib.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/libffi.so.8
Using emulated /tmp/_MEIfKg5rV/lib-dynload/_heapq.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/_posixsubprocess.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/select.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/math.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/_opcode.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/_pickle.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/_socket.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/array.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/binascii.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so
Using native(wrapped) libbz2.so.1
Using emulated /tmp/_MEIfKg5rV/lib-dynload/_lzma.cpython-38-x86_64-linux-gnu.so
Using native(wrapped) liblzma.so.5
Using emulated /tmp/_MEIfKg5rV/lib-dynload/grp.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/_datetime.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/pyexpat.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/_bisect.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/_sha512.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/lib-dynload/_random.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/wrapt/_wrappers.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIfKg5rV/shiboken6/Shiboken.abi3.so
Using emulated /tmp/_MEIfKg5rV/libshiboken6.abi3.so.6.2
Using emulated /tmp/_MEIfKg5rV/libstdc++.so.6
Using emulated /tmp/_MEIfKg5rV/libgcc_s.so.1
Error: Symbol __wmemmove_chk not found, cannot apply R_X86_64_JUMP_SLOT @0xffff99f56020 (0x9a040) in /tmp/_MEIfKg5rV/libstdc++.so.6
Warning: Weak Symbol _ITM_memcpyRtWn not found, cannot apply R_X86_64_JUMP_SLOT @0xffff99f56080 (0x9a100)
Warning: Weak Symbol _ITM_RU1 not found, cannot apply R_X86_64_JUMP_SLOT @0xffff99f566a8 (0x9ad50)
Warning: Weak Symbol _ZGTtdlPv not found, cannot apply R_X86_64_JUMP_SLOT @0xffff99f56b20 (0x9b640)
Error: Symbol __mbsnrtowcs_chk not found, cannot apply R_X86_64_JUMP_SLOT @0xffff99f56e18 (0x9bc30) in /tmp/_MEIfKg5rV/libstdc++.so.6
Warning: Weak Symbol _ITM_RU8 not found, cannot apply R_X86_64_JUMP_SLOT @0xffff99f57020 (0x9c040)
Error: Symbol __wmemset_chk not found, cannot apply R_X86_64_JUMP_SLOT @0xffff99f57220 (0x9c440) in /tmp/_MEIfKg5rV/libstdc++.so.6
Error: Symbol __mbsrtowcs_chk not found, cannot apply R_X86_64_JUMP_SLOT @0xffff99f57270 (0x9c4e0) in /tmp/_MEIfKg5rV/libstdc++.so.6
Warning: Weak Symbol _ITM_memcpyRnWt not found, cannot apply R_X86_64_JUMP_SLOT @0xffff99f574d0 (0x9c9a0)
Warning: Weak Symbol _ZGTtnam not found, cannot apply R_X86_64_JUMP_SLOT @0xffff99f57ce8 (0x9d9d0)
Error: relocating Plt symbols in elf libstdc++.so.6
Error initializing needed lib libstdc++.so.6
Error loading one of needed lib
Error initializing needed lib libshiboken6.abi3.so.6.2
Error loading one of needed lib
Error initializing needed lib /tmp/_MEIfKg5rV/shiboken6/Shiboken.abi3.so
2797|SIGSEGV @0x349e4284 (???(/home/cypellab/Documents/ControlCenter+0x349e4284)) (x64pc=0x400d3/???:"???", rsp=0x101ff56a8, stack=0x101800000:0x102000000 own=(nil) fp=0x101ff5740), for accessing 0x218 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x0000ffff9b329048 RSP-0x18:0x000000010273b640 RSP-0x10:0x00000001020726b2 RSP-0x08:0x00000000705881b0
RSP+0x00:0x0000ffff9b4674b3 RSP+0x08:0x0000000000000000 RSP+0x10:0x0000ffff9b32302d RSP+0x18:0x000000010271c590
RAX:0x0000000070583250 RCX:0xffffffffffffffff RDX:0x0000000000000000 RBX:0x0000000102717c90
RSP:0x0000000101ff56a8 RBP:0x0000000101ff5740 RSI:0x0000000000000002 RDI:0x0000000102740190
R8:0x0000ffff9b52dd70 R9:0x0000000101ff55d0 R10:0x0000000101ff5957 R11:0x00000001027363e0
R12:0x0000000102740190 R13:0x000000010271c590 R14:0x0000000000000000 R15:0x0000ffff9b5228c5
2790|SIGSEGV @0xffffa75bf200 (???(/lib/aarch64-linux-gnu/libc.so.6+0xffffa75bf200)) (x64pc=0x50060/???:"???", rsp=0x101ffc0a8, stack=0x101800000:0x102000000 own=(nil) fp=0x5ee609f8), for accessing 0x3e800000ae6 (code=-6/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x0000000101ffc110 RSP-0x18:0x0000000101fff170 RSP-0x10:0x000000005ee061e0 RSP-0x08:0x0000000000000003
RSP+0x00:0x0000000000407646 RSP+0x08:0x000000005ee35608 RSP+0x10:0x0000008b00000000 RSP+0x18:0x0000000000000001
RAX:0x000000000000000c RCX:0x0000000000000001 RDX:0x0000000000000000 RBX:0x000000005ee609f8
RSP:0x0000000101ffc0a8 RBP:0x000000005ee609f8 RSI:0x00000000350b9f80 RDI:0x000000000000000b
R8:0x0000000000000000 R9:0x0000000101ffc110 R10:0x0000000000000000 R11:0x0000000000000000
R12:0x0000000000000aed R13:0x0000000000000001 R14:0x0000000000000000 R15:0x0000000000000001

**Comment by ksco** [comment]
Can you try on the latest main and paste the log here also?

**Comment by ptitSeb** [comment]
I have added the 2 missings symbols

**Comment by LionheartPL** [comment]
Hi everyone, thanks for the quick replies. I've tried again with the newest build and got the following log:
`box64 ControlCenter
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 25 entries
Box64 with Dynarec v0.2.3 04a74371 built on May  8 2023 16:27:16
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 49 Env var
Looking for ControlCenter
Rename process to "ControlCenter"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libz.so.1
Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 25 entries
Box64 with Dynarec v0.2.3 04a74371 built on May  8 2023 16:27:16
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 52 Env var
Looking for /home/cypellab/Documents/ControlCenter
Rename process to "ControlCenter"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libz.so.1
Using emulated /tmp/_MEIOP5mkM/libpython3.8.so.1.0
Using native(wrapped) libm.so.6
Using emulated /tmp/_MEIOP5mkM/lib-dynload/_struct.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/zlib.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/libffi.so.8
Using emulated /tmp/_MEIOP5mkM/lib-dynload/_heapq.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/_posixsubprocess.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/select.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/math.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/_opcode.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/_pickle.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/_socket.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/array.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/binascii.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so
Using native(wrapped) libbz2.so.1
Using emulated /tmp/_MEIOP5mkM/lib-dynload/_lzma.cpython-38-x86_64-linux-gnu.so
Using native(wrapped) liblzma.so.5
Using emulated /tmp/_MEIOP5mkM/lib-dynload/grp.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/_datetime.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/pyexpat.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/_bisect.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/_sha512.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/_random.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/wrapt/_wrappers.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/shiboken6/Shiboken.abi3.so
Using emulated /tmp/_MEIOP5mkM/libshiboken6.abi3.so.6.2
Using emulated /tmp/_MEIOP5mkM/libstdc++.so.6
Using emulated /tmp/_MEIOP5mkM/libgcc_s.so.1
Warning: Weak Symbol _ITM_memcpyRtWn not found, cannot apply R_X86_64_JUMP_SLOT @0x101806080 (0x9a100)
Warning: Weak Symbol _ITM_RU1 not found, cannot apply R_X86_64_JUMP_SLOT @0x1018066a8 (0x9ad50)
Warning: Weak Symbol _ZGTtdlPv not found, cannot apply R_X86_64_JUMP_SLOT @0x101806b20 (0x9b640)
Warning: Weak Symbol _ITM_RU8 not found, cannot apply R_X86_64_JUMP_SLOT @0x101807020 (0x9c040)
Warning: Weak Symbol _ITM_memcpyRnWt not found, cannot apply R_X86_64_JUMP_SLOT @0x1018074d0 (0x9c9a0)
Warning: Weak Symbol _ZGTtnam not found, cannot apply R_X86_64_JUMP_SLOT @0x101807ce8 (0x9d9d0)
Warning, resizing of TLS occurred! size: 0->65536 / n_elfs: 1->1
Using emulated /tmp/_MEIOP5mkM/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/libopenblasp-r0-ae94cfde.3.9.dev.so
Using emulated /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Using emulated /tmp/_MEIOP5mkM/libquadmath-2d0c479f.so.0.0.0
Using emulated /tmp/_MEIOP5mkM/libz-eb09ad1d.so.1.2.3
Error: Symbol sinhl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff8118 (0x19bfe) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol jnl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff8190 (0x19cee) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol csqrtl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff8290 (0x19eee) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol atan2l not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff82f8 (0x19fbe) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol lroundl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff83a0 (0x1a10e) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol coshl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff83b0 (0x1a12e) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol tanl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff84c0 (0x1a34e) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol csinl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff8600 (0x1a5ce) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol roundl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff8630 (0x1a62e) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol ynl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff8740 (0x1a84e) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol atanl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff8748 (0x1a85e) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol sinl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff87e0 (0x1a98e) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol clogf not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff8820 (0x1aa0e) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol cabsl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff8868 (0x1aa9e) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol ccosl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff8b00 (0x1afce) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol clogl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff8c00 (0x1b1ce) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol cexpl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff8c18 (0x1b1fe) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol tanhl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff8d08 (0x1b3de) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: Symbol cosl not found, cannot apply R_X86_64_JUMP_SLOT @0x103ff8e78 (0x1b6be) in /tmp/_MEIOP5mkM/libgfortran-2e0d59d6.so.5.0.0
Error: relocating Plt symbols in elf libgfortran-2e0d59d6.so.5
Error initializing needed lib libgfortran-2e0d59d6.so.5.0.0
Error loading one of needed lib
Error initializing needed lib libopenblasp-r0-ae94cfde.3.9.dev.so
Error loading one of needed lib
Error initializing needed lib /tmp/_MEIOP5mkM/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so
Using emulated /tmp/_MEIOP5mkM/lib-dynload/_queue.cpython-38-x86_64-linux-gnu.so
2115|SIGSEGV @0x349c6320 (???(/home/cypellab/Documents/ControlCenter+0x349c6320)) (x64pc=0x400d3/???:"???", rsp=0x100857d68, stack=0x100060000:0x100860000 own=(nil) fp=0x100857e00), for accessing 0x4 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x0000000100900048 RSP-0x18:0x00000001018ab100 RSP-0x10:0x0000000100c626b2 RSP-0x08:0x000000003bea91d0
RSP+0x00:0x0000000100a3e4b3 RSP+0x08:0x0000000000000000 RSP+0x10:0x00000001008fa02d RSP+0x18:0x000000010188ffb0
RAX:0x000000003bea4270 RCX:0xffffffffffffffff RDX:0x0000000000000000 RBX:0x000000010189f630 
RSP:0x0000000100857d68 RBP:0x0000000100857e00 RSI:0x0000000000000002 RDI:0x00000001018a43d0 
 R8:0x0000000100b04d70  R9:0x0000000100857c90 R10:0x0000000100858017 R11:0x0000000101940120 
R12:0x00000001018a43d0 R13:0x000000010188ffb0 R14:0x0000000000000000 R15:0x0000000100af98c5 
2110|SIGSEGV @0xffffae2103f0 (???(/lib/aarch64-linux-gnu/libc.so.6+0xffffae2103f0)) (x64pc=0x50060/???:"???", rsp=0x10085bf38, stack=0x100060000:0x100860000 own=(nil) fp=0x3af30a68), for accessing 0x3e80000083e (code=-6/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x000000010085bfa0 RSP-0x18:0x000000010085f000 RSP-0x10:0x000000003aed6350 RSP-0x08:0x0000000000000003
RSP+0x00:0x0000000000407646 RSP+0x08:0x000000003af05678 RSP+0x10:0x0000008b00000000 RSP+0x18:0x0000000000000001
RAX:0x000000000000000c RCX:0x0000000000000001 RDX:0x0000000000000000 RBX:0x000000003af30a68 
RSP:0x000000010085bf38 RBP:0x000000003af30a68 RSI:0x00000000350aeef0 RDI:0x000000000000000b 
 R8:0x0000000000000001  R9:0x000000010085bfa0 R10:0x0000000000000000 R11:0x0000000000000000 
R12:0x0000000000000843 R13:0x0000000000000001 R14:0x0000000000000000 R15:0x0000000000000001 
`

**Comment by ksco** [comment]
These are some `long double _Complex` functions such as `ccosl` are missing. And the `long double _Complex` type is directly passed through the stack, which seems tricky to implement. @ptitSeb

**Comment by ptitSeb** [comment]
Yeah, I need to analyse how `long double complex` are passed through. I'll do the wrapping for those. But I'll need some time to analyse first

**Comment by happyme531** [comment]
Same issue for numpy.

```log
Using emulated /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so
Using emulated /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so
Using emulated /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/bin/../lib/libgcc_s.so.1
Using emulated /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Using emulated /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libquadmath-96973f99.so.0.0.0
Using native(wrapped) libz.so.1
Warning: Weak Symbol __gmon_start__ not found, cannot apply R_X86_64_JUMP_SLOT @0x3f0623b0f8 (0x20f6)
Error: Symbol roundl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f054760d0 (0x19c36) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol ccosl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476180 (0x19d96) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol clogl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476318 (0x1a0c6) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol coshl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476450 (0x1a336) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol cabsl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476660 (0x1a756) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol ynl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f054766b0 (0x1a7f6) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Warning: Weak Symbol __gmon_start__ not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476760 (0x1a956)
Error: Symbol lroundl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f054767d0 (0x1aa36) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol atan2l not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476888 (0x1aba6) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol jnl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f054768c8 (0x1ac26) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol tanl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476a28 (0x1aee6) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol tanhl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476a30 (0x1aef6) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol sinl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476b50 (0x1b136) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol csqrtl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476b90 (0x1b1b6) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol cosl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476d50 (0x1b536) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol atanl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476d70 (0x1b576) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol csinl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476dc0 (0x1b616) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol clogf not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476e38 (0x1b706) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol sinhl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476e60 (0x1b756) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: Symbol cexpl not found, cannot apply R_X86_64_JUMP_SLOT @0x3f05476e98 (0x1b7c6) in /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libgfortran-040039e1.so.5.0.0
Error: relocating Plt symbols in elf libgfortran-040039e1.so.5
Error initializing needed lib libgfortran-040039e1.so.5.0.0
Error loading one of needed lib
Error initializing needed lib libopenblas64_p-r0-0cf96a72.3.23.dev.so
Error loading one of needed lib
Error initializing needed lib /home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "/home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: Cannot dlopen("/home/firefly/rk3588_prod/rknn-toolkit2-arm64/venv3.10/lib/python3.10/site-packages/numpy/core/_multiarray_umath.
```

**Comment by ptitSeb** [comment]
This should be fixed. Support for floaat/double/long double complex have been added to box64 some time ago.
